/**
 * 本站的服务端代码 —— 两块：点歌台的取数接口，和「AI 版沉麟」的对话接口。
 *
 * 在这个文件出现之前，本站是纯 `[assets]` 的静态资源 Worker，没有一行代码在线上跑。
 * 加了 `wrangler.toml` 的 `main` 之后多了**运行期故障面**：这里抛异常就是线上 500。
 * 所以每一条路径都要有兜底，宁可返回一句中文人话，不要让异常裸奔。
 * 这道「单向门」第 11 轮已批准（原定 R6 阶段②走，点歌台把它提前了）。
 *
 * 做什么：
 * - `/api/music/*`：把浏览器不能直连的 `yinyueku.cn/api.php` 转成五条同源只读 GET。
 * - `/api/chat`：R6 阶段②。Workers AI + 整个知识库当依据，流式回答，回答完落库到
 *   Durable Object（R32 定的「改成落库、永久保留」）。
 *
 * 不做什么：**不中转媒体字节**。音频与封面的直链都自带 CORS（音频还带 Range），
 * 浏览器直接去 `music.126.net` / `p3.music.126.net` 拉，13 MB 的流量一个字节都不进
 * Worker 配额。
 *
 * 上游契约、四条坑、榜单白名单全在 `src/data/jukebox.ts` 的顶部注释里，改这里之前先看那个。
 * 对话那半边的模型选型账与提示词决议在 `src/data/chat.ts`。
 *
 * 缓存头必须在这里自己设：`public/_headers` **不作用于 Worker 生成的响应**
 * （官方文档原文 "Custom headers are not applied to responses generated by your
 * Worker code"）。静态资源仍走 `_headers`，两套互不相干。
 */
import {
  isChartId,
  LIST_MAX_N,
  SEARCH_MAX_N,
  SEARCH_MAX_Q,
  type JukeTrack,
} from './data/jukebox';
import {
  buildSystem,
  FALLBACK_MODEL,
  MAX_TOKENS,
  MSG_MAX,
  TEMPERATURE,
  type KbItem,
} from './data/chat';
import { SHAPES, onceUrl, type Proto, type Shape, type Turn } from './data/proto';
/** 服务商预设与探测用的对照端点（R41③）。端点表在那个文件里，实测记录也在 */
import { CONTROLS } from './data/providers';
/**
 * 仓库里现有内容的原样快照（R41②）。**构建期生成、编译进 Worker 包**，
 * 不是静态资源 —— 为什么这么绕，见 `scripts/gen-content.mjs` 顶部那段
 * （一句话：`dist/` 全是公开可取的，而草稿正文不该有 URL）。
 */
import { CONTENT } from './data/content.generated';

/** DO 类必须从入口文件导出，`wrangler.toml` 的 `[exports.ChatLog]` 才找得到它 */
export { ChatLog } from './chat-log';

/**
 * 只声明用得到的绑定。**刻意不引 `@cloudflare/workers-types`** ——
 * 它的全局 `Request`/`Response` 会和 Astro 的 `lib.dom` 打架，
 * 为一个 Fetcher 类型换来全站类型冲突不值。
 */
interface Env {
  ASSETS: { fetch(req: Request): Promise<Response> };
  /** Workers AI。`[ai] binding = "AI"`，免费档 10,000 neurons/天 */
  AI: { run(model: string, input: Record<string, unknown>): Promise<unknown> };
  /** 对话落库。一个会话一个 DO 实例，名字就是会话 id */
  CHAT: {
    idFromName(name: string): unknown;
    get(id: unknown): { fetch(req: Request): Promise<Response> };
  };
  /**
   * 保险丝。R32 他选了「额度护栏先不设」，这不是护栏 —— 是出事时的关停开关：
   * `npx wrangler secret put CHAT_OFF`（值随便非空），`/api/chat` 立刻只回一句人话，
   * 不改代码、不重新构建、不影响点歌台。
   */
  CHAT_OFF?: string;
  /**
   * 对话上游的主路（R34）。三样一起给才生效，缺一样就退回 `env.AI`。
   * **值里有服务商信息，所以三样都只在 secret 里** —— 仓库是公开的，
   * 而他要求站上不体现这条链路的任何信息。代码里因此只有变量名。
   */
  CHAT_BASE?: string;
  CHAT_KEY?: string;
  CHAT_MODEL?: string;
  /** 请求格式（R39）。`openai` / `responses` / `anthropic` / `gemini`，缺省 `openai` */
  CHAT_PROTO?: string;
  /**
   * 后台（`/admin`）的口令哈希与 cookie 签名密钥 —— R20② 那把锁，方案 B。
   *
   * `ADMIN_HASH` 格式：`pbkdf2$<迭代数>$<saltBase64>$<hashBase64>`。
   * 生成命令在 [部署运维](../docs/部署运维.md#后台口令) 里，**明文口令不进任何文件**。
   * 迭代数刻意只有一万：Workers Free 是 10 ms CPU／请求，而这把锁的威胁模型里
   * **哈希本身不可能泄漏**（只在 secret 里，不落库、不进仓库），
   * 离线爆破的前提不成立，所以不需要 OWASP 那个量级的慢哈希。
   *
   * 两样都没配时 `/admin` 会显示「还没设口令」并给出命令，**不会变成一把开着的锁**。
   */
  ADMIN_HASH?: string;
  ADMIN_SECRET?: string;
}

interface Ctx {
  waitUntil(p: Promise<unknown>): void;
}

const UPSTREAM = 'http://yinyueku.cn/api.php';

/** 上游是单点、证书都过期了，别让访客陪它一起等 */
const TIMEOUT_MS = 8000;

const API_PREFIX = '/api/music/';

/**
 * 各端点的缓存时长。
 *
 * `url` 一律不缓存。直链路径里带时间戳（`/20260822180905/`）：同一个 URL 连测
 * 6 分钟（0/60/180/360 秒）全是 206、总长恒为 11039085 —— 所以「播到一半链接
 * 过期」这条不成立，R14 拿它排除过一次误判。但**更长的有效期仍然未知**，
 * 而缓存一个已失效的直链的代价是「点了没声音」，收益只是省一次上游往返，
 * 不划算。择优选源那条路更不能缓存：它的结果取决于当时能探到的候选。
 *
 * `list` 只有 5 分钟：歌单是活的 —— 站主往「沉麟推荐」里加一首歌，不该等一小时
 * 才在站上看见（R23 就是这么报上来的：「改了歌单，刷新后没有变化」）。而且
 * `wrangler dev` 下这层缓存由 miniflare 持久化到 `.wrangler/state/v3/cache/`，
 * **重启进程也不清**，一小时的 TTL 在本地开发里就是一小时看不见改动。
 * 5 分钟仍然挡住了「一屏点开十次歌单」那种连续往返。
 *
 * `pic` 一天：封面直链是长期地址（自带 `max-age=31536000`，路径里没有 token 也没有
 * 时间戳），与 `url` 那条完全不同 —— 缓存它没有「过期了就没声音」的风险。
 */
const CACHE = {
  list: 'public, max-age=300',
  search: 'public, max-age=300',
  lyric: 'public, max-age=86400',
  pic: 'public, max-age=86400',
  none: 'no-store',
} as const;

/** LRC 时间戳。上游把错误信息也塞在 lyric 字段里，靠这个正则区分真歌词 */
const HAS_STAMP = /\[\d{1,3}:\d{1,2}/;

function json(data: unknown, cache: string, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': cache,
      // 接口不该被搜到，也不该给这个中文个人站招来音乐检索词
      'x-robots-tag': 'noindex',
    },
  });
}

/** 失败一律 no-store，不然会把一次上游抖动缓存一整天 */
const fail = (status: number, msg: string) => json({ error: msg }, CACHE.none, status);

/** 数字 id 也当字符串用；其余类型（null/对象）一律当缺失 */
function txt(v: unknown): string {
  if (typeof v === 'string') return v;
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return '';
}

function pick(data: unknown, key: string): string {
  return data && typeof data === 'object'
    ? txt((data as Record<string, unknown>)[key])
    : '';
}

/**
 * 打上游。抛出的 Error 的 message 全是我自己写的中文 ——
 * **上游响应体一个字都不外泄**（它的错误页是 HTML，里面还有它自己的路径）。
 */
async function upstream(params: Record<string, string>): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(UPSTREAM, {
      method: 'POST',
      // 这个头去掉上游就返回 HTML 错误页而不是 JSON（实测），不能省
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(params),
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    throw new Error('连不上曲库，等会儿再试');
  }

  if (!res.ok) throw new Error('曲库那边不太好（' + res.status + '）');

  const text = await res.text();
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new Error('曲库返回的不是 JSON');
  }
}

/** 一条上游记录 → 出口形状。缺关键字段就返回 null，宁可丢掉也不给前端半条 */
function toJuke(raw: unknown): JukeTrack | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  const songId = txt(r.id);
  const urlId = txt(r.url_id) || songId;
  const source = txt(r.source);
  const sign = txt(r.sign);
  if (!songId || !urlId || !source || !sign) return null;

  const artist = Array.isArray(r.artist)
    ? r.artist.map(txt).filter(Boolean).join(' / ')
    : txt(r.artist);

  return {
    songId,
    title: txt(r.name) || '未命名',
    artist,
    album: txt(r.album),
    urlId,
    lyricId: txt(r.lyric_id) || songId,
    // 封面 id **不进上面那道必填校验**：没有封面照样能播，不能因为缺它把整条候选判死
    picId: txt(r.pic_id),
    source,
    sign,
  };
}

function toList(data: unknown, limit: number): JukeTrack[] {
  if (!Array.isArray(data)) throw new Error('曲库返回的不是一个列表');
  const out: JukeTrack[] = [];
  for (const it of data) {
    const t = toJuke(it);
    if (t) out.push(t);
    if (out.length >= limit) break;
  }
  return out;
}

const clamp = (n: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, n));

/* ==========================================================================
   择优选源 —— 「部分 VIP 歌曲播不全」的真正解法

   R14 之前的判断是「上游对 VIP 只给 30 秒试听」，三轮实测把它推翻了：

   ① `br`（码率）参数无效：同一首歌 br=128/320/740/999/flac/不传，六种取值
      返回同一个 720813 B 的文件。所以「传个高码率就有完整版」是死路。
   ② 直链不是短命的：同一个 URL 连测 6 分钟全是 206，总长恒定。
   ③ **决定性的一条** —— 同一首歌、同一个源，两次搜索取到的东西不一样：
      《想你就写信 (Live)》第一轮 720813 B（≈0:18），第三轮 9550125 B（≈3:59）。
      而且同一次搜索的候选里，完整版与片段是**并排**的：
        《想你就写信》 tencent 9550376 B ≈3:59   ／ tencent  578573 B ≈0:14
        《不为谁而作的歌》tencent 10634755 B ≈4:26 ／ tencent 2552241 B ≈1:04
        《起风了》     tencent 12519132 B ≈5:13 ／ tencent 5215076 B ≈2:10
      原来的代码是「搜索结果第一条直接播」，第一条正好是片段时，
      看起来就完全像「这首 VIP 播不全」。

   所以这不是版权墙，是挑错了候选。修法：在**上游本来就免费返回**的同名候选里
   挑字节数最大的那条 —— 不涉及任何授权绕过，也不需要 VIP 凭据
   （Worker 是公开的，凭据一进去任何访客都能拿到解锁直链，等于替站长对外分发）。
   实测五首典型歌（想你就写信／晴天／不为谁而作的歌／恋人／起风了）5/5 都挑到完整版。
   ========================================================================== */

/**
 * 启动择优的字节下限。**它只决定「要不要去挑」，不用来判断完整性** ——
 * 实测的片段里有 5215076 B（《起风了》2:10，完整是 5:13）这种，
 * 绝对阈值判不出来。真正的判据是「候选里的最大值」。
 */
const MIN_FULL_BYTES = 2 * 1024 * 1024;

/** 并发探的候选上限。每条 1 次取链 + 1 次探头，6 条 = 12 个 subrequest，
    加首选与两次搜索共 16，离免费档的 50 还远。等待 I/O 不计入 CPU 时间，
    所以也撞不到 10ms 那条线 */
const PICK_MAX = 6;

/** 每源搜多少条。上游 count 是下限，20 够把同名的都捞进来 */
const PICK_COUNT = 20;

/**
 * 择优时搜哪些源。上游真实源只有三个：`netease`、`tencent`、`kugou`
 * （`kuwo`/`baidu`/`xiami` 退化成 tencent，`migu` 返回空）。
 * kugou 实测 8 次里 6 次取不到直链，不值得占一个候选名额。
 */
const PICK_SOURCES = ['netease', 'tencent'] as const;

/**
 * 归一化歌名／艺人用于比对：括号里的内容整段丢掉（`(Live)`、`（沉浸版）` 都是噪音），
 * 再去掉所有非字母非数字非汉字的字符并转小写。
 * 「想你就写信 (Live)」与「想你就写信」归一化后相等；「李荣浩-」「李荣浩.」都归一到「李荣浩」。
 */
function norm(s: string): string {
  return s
    .replace(/[(（[【][^)）\]】]*[)）\]】]/g, '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]/gu, '');
}

/**
 * 艺人算不算同一个。用包含关系而不是相等：上游的艺人字段常带脏尾巴或合作者
 * （实测有「李荣浩-」「李荣浩. / Sazablue」「周杰伦/李硕/达布希勒图/张鑫」），
 * 要求相等会把正确的候选全滤掉。任一侧为空就不作要求。
 */
function sameArtist(a: string, b: string): boolean {
  const x = norm(a);
  const y = norm(b);
  if (!x || !y) return true;
  return x.includes(y) || y.includes(x);
}

/**
 * 探这条直链有多少字节。`Range: bytes=0-9` 只拉 10 个字节，读的是响应头里的
 * `content-range: bytes 0-9/11039085` —— 音频字节仍然不进 Worker 配额。
 * 探不到返回 0：**这表示「不知道」，不表示「是片段」**，调用方要区分对待。
 */
async function probeBytes(link: string): Promise<number> {
  let res: Response;
  try {
    res = await fetch(link, {
      headers: { range: 'bytes=0-9' },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    return 0;
  }

  // 那 10 个字节也不留着占连接
  try {
    await res.body?.cancel();
  } catch {
    /* 已经关了就算了 */
  }

  const cr = res.headers.get('content-range') ?? '';
  if (cr.includes('/')) {
    const total = Number(cr.slice(cr.indexOf('/') + 1));
    if (Number.isFinite(total) && total > 0) return total;
  }

  // 不认 Range 的服务器会回 200 + 整个文件，这时 content-length 就是全长
  if (res.status === 200) {
    const len = Number(res.headers.get('content-length'));
    if (Number.isFinite(len) && len > 0) return len;
  }
  return 0;
}

/** 取一条直链。签名不对时上游返回 `{"url":"签名错误！"}`（HTTP 200、JSON 合法、
    字段名也对），所以必须看内容 —— 拿不到就返回空串 */
async function getLink(id: string, source: string, sign: string): Promise<string> {
  const link = pick(await upstream({ types: 'url', id, source, sign }), 'url');
  return link.startsWith('https://') ? link : '';
}

/** 一个源搜一次。搜不到／上游抖动都当「这个源没结果」——
    首选直链已经在手上了，不能让择优失败把整个请求带崩 */
async function searchIn(source: string, q: string): Promise<JukeTrack[]> {
  try {
    const data = await upstream({
      types: 'search',
      count: String(PICK_COUNT),
      pages: '1',
      name: q,
      source,
    });
    return toList(data, PICK_COUNT);
  } catch {
    return [];
  }
}

interface Cand {
  url: string;
  bytes: number;
}

/** 取链 + 探头，两步都可能失败，失败一律当 0 字节淘汰掉 */
async function weigh(t: JukeTrack): Promise<Cand> {
  try {
    const link = await getLink(t.urlId, t.source, t.sign);
    if (!link) return { url: '', bytes: 0 };
    return { url: link, bytes: await probeBytes(link) };
  } catch {
    return { url: '', bytes: 0 };
  }
}

/**
 * 在同名候选里找字节数最大的那条。找不到比 `floor` 更大的就返回 null。
 * `skip` 是首选的 `source:urlId`，它已经探过了，不重复花两个 subrequest。
 */
async function pickBest(
  name: string,
  artist: string,
  floor: number,
  skip: string,
): Promise<Cand | null> {
  const q = artist ? `${name} ${artist}` : name;
  const found = await Promise.all(PICK_SOURCES.map((s) => searchIn(s, q)));

  const want = norm(name);
  const seen = new Set<string>([skip]);
  const pool: JukeTrack[] = [];
  for (const list of found) {
    for (const t of list) {
      // 歌名要求归一化后相等（包含关系会把「老街」也算进「恋人」的候选）；
      // 艺人放宽到包含
      if (norm(t.title) !== want || !sameArtist(t.artist, artist)) continue;
      const key = `${t.source}:${t.urlId}`;
      if (seen.has(key)) continue;
      seen.add(key);
      pool.push(t);
      if (pool.length >= PICK_MAX) break;
    }
    if (pool.length >= PICK_MAX) break;
  }
  if (!pool.length) return null;

  const weighed = await Promise.all(pool.map(weigh));
  let best: Cand | null = null;
  for (const c of weighed) {
    if (c.url && c.bytes > floor && (!best || c.bytes > best.bytes)) best = c;
  }
  return best;
}

/* ==========================================================================
   AI 版沉麟 —— R6 阶段②

   整条链：浏览器 POST 一句话 → 这里拼「系统提示词 + 整个知识库 + 最近 3 轮」→
   Workers AI 流式吐字 → 流 tee 成两路，一路直给浏览器、一路自己读完写进 DO。

   **检索是「全给」，不是向量检索**：知识库现在 24 条、约 9000 tokens，Qwen3 的窗口
   是 32k，全塞进去比做检索更准也更简单（漏检的代价是「他明明写过却说没写过」）。
   代价是每次对话的输入 token 固定偏高 ≈ 每天 196 次。**条目涨到 60 条以上就得改**：
   那时输入会超过 2 万 token，一天只剩几十次。改法是先按关键词粗筛再拼，不必上向量库。
   ========================================================================== */

const CHAT_PATH = '/api/chat';

/** 会话 id 的形状。它要当 DO 的名字用，所以字符集必须收紧 */
const SESSION_RE = /^[0-9a-f-]{8,64}$/i;

/**
 * 会话号 = 访客 IP 的指纹（R42 他要的「同一 IP 使用相同会话」）。
 *
 * ## 为什么改成服务端派生
 *
 * R41 及之前，会话号是**前端生成的一个 uuid**，存在 `sessionStorage` 里 ——
 * 那意味着一个标签页一份、关掉标签就换新的。后果有三个，都是刚做完接管才看清的：
 * 访客一刷新就换了一条会话，他正在接的那个人突然「不见了」；同一个人开两个标签
 * 在后台是两条线；换个浏览器回来又是新的一条。
 *
 * 而 IP 只有服务端知道（`cf-connecting-ip`，Cloudflare 注入，访客改不了）。
 * 所以会话号必须在这儿算，前端传什么都不作为会话号采信。
 *
 * ## 为什么取 hash 而不是直接用 IP
 *
 * 会话号就是 Durable Object 的实例名，它会出现在后台的接口参数、`console` 日志里。
 * IP 不该在那些地方裸奔。**这不是加密**（IPv4 空间小，能枚举），只是不让它一眼可读；
 * 真正的保护是「记录要登录才能读」。
 *
 * 不加盐是刻意的：加了就与某个 secret 绑死，**那个 secret 一换，所有会话号跟着变**
 * （等于历史记录集体失联）。会话号本身不是凭据，不需要防枚举。
 *
 * 取前 16 字节 = 32 个十六进制字符，正好落在 `SESSION_RE` 里，
 * 也不会与配置实例的名字 `'config'` 相撞（那里面有 n/g/i/o，十六进制里没有）。
 */
async function sessionOf(ip: string): Promise<string> {
  const bits = await crypto.subtle.digest('SHA-256', enc.encode('ip:' + ip));
  return [...new Uint8Array(bits).slice(0, 16)]
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * 窗口号的形状（R42）。前端 `sessionStorage` 里那个 uuid ——
 * 它从「会话号」降级成了「这一个浏览器窗口」。
 *
 * 会话按 IP 合并之后，同一条会话下可能有好几个不同的人（学校、公司、运营商 NAT，
 * 手机的 CGNAT 更是常态）。窗口号管两件事：**喂给模型的上下文按它过滤**、
 * **接管时那句话按它定向**。不这么分的话，隔壁那个人说的话会串进你的对话里。
 */
const TAB_RE = /^[0-9a-zA-Z_-]{8,64}$/;

/** 知识库在 isolate 里缓存 5 分钟，省掉每次对话都读一遍 `/kb.json` 的 subrequest */
const KB_TTL_MS = 5 * 60 * 1000;
let kbCache: { at: number; items: KbItem[] } | null = null;

/**
 * 读知识库。走 `env.ASSETS.fetch('/kb.json')` —— 那是构建产物里的静态文件，
 * 由 `src/pages/kb.json.ts` 从 `src/content/kb/` 生成。
 * 这么绕是因为 `astro:content` 只存在于 Astro 构建期，这个文件 import 不到它。
 */
async function loadKb(env: Env, base: string): Promise<KbItem[]> {
  if (kbCache && Date.now() - kbCache.at < KB_TTL_MS) return kbCache.items;

  const res = await env.ASSETS.fetch(new Request(new URL('/kb.json', base)));
  if (!res.ok) throw new Error('知识库读不出来');

  const data = (await res.json()) as { items?: KbItem[] };
  const items = Array.isArray(data.items) ? data.items : [];
  // 空知识库比答错更糟：那会让模型完全靠自己编，而 R32 允许它编的前提是「有底座」
  if (!items.length) throw new Error('知识库是空的');

  kbCache = { at: Date.now(), items };
  return items;
}

const stubOf = (env: Env, session: string) => env.CHAT.get(env.CHAT.idFromName(session));

/**
 * 配置实例。`'config'` 不可能与会话号相撞 —— `SESSION_RE` 只放行 `[0-9a-f-]`，
 * 而这个名字里有 `n`、`g`、`i`、`o`。
 */
const cfgStub = (env: Env) => stubOf(env, 'config');

/** 读「上一次为什么没走通」。后台面板顶上显示它 —— 排查上游问题的第一现场 */
async function lastWhy(env: Env): Promise<string> {
  try {
    const res = await cfgStub(env).fetch(new Request('https://chat.do/cfg'));
    if (!res.ok) return '';
    const d = (await res.json()) as { cfg?: Record<string, string> };
    return d.cfg?.lastwhy ?? '';
  } catch {
    return '';
  }
}

/** 一次对话真正用到的配置 */
interface Cfg {
  /**
   * 上游线路，**按顺序试**（R41③）。第一条打不通就换第二条，全打不通才掉 Workers AI 兜底。
   *
   * 为什么从「一条线路」改成「一串」：他的要求逐字是「我必须能使用国内的服务商，
   * 无论你使用什么办法」。国内那几家从 Cloudflare 的境外边缘打过去**不保证通**
   * （R37 那次就是上游拦 workerd），而「通不通」只有打了才知道。
   * 一条线路的配置下，赌错就是整个功能停摆；一串线路下，赌错只是换下一条。
   *
   * 典型用法：主线填国内服务商（便宜、中文好），备线填一个境外可达的，
   * 两条都挂了还有 Workers AI。
   */
  routes: Route[];
  off: boolean;
}

/** 一条上游线路。四样缺一样这条就是不完整的，`chat()` 会直接跳过它 */
interface Route {
  base: string;
  key: string;
  models: string[];
  /** 请求格式（R39）。四种，见 `data/proto.ts` */
  proto: Proto;
  /**
   * 这家服务商在**中国大陆**（R39 他要的那个开关）。
   *
   * 它不改变请求怎么发，只改变后台怎么解读失败：线上是 Cloudflare 的境外边缘出网，
   * 跨境到大陆的链路本来就不稳。**但不要把它读成「大陆的一律打不通」** ——
   * R37 那次的结论是「那一家中转站在区别对待 workerd」（同一个 Worker 打
   * `api.openai.com` 0.5 秒就拿到 401）。到底通不通用后台的「探一下能不能连」当场测。
   */
  domestic: boolean;
}

/** 线路上限。免费档 subrequest 是 50 个／请求，三条线路各两三个模型离得还远 */
const ROUTE_MAX = 3;

const asProto = (v: unknown): Proto => {
  const s = typeof v === 'string' ? v : '';
  return (s in SHAPES ? s : 'openai') as Proto;
};

const asModels = (v: unknown): string[] =>
  String(typeof v === 'string' ? v : '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);

/**
 * 生效配置 = **后台改过的值覆盖 secret 里的默认值**。
 *
 * 为什么要能在后台改：这家上游的模型可用性会漂移（台账 R34 记的实测 —— 同一个模型
 * 20 分钟前还好，再调就「没有可用通道」）。改一次模型要走 `wrangler secret put` +
 * 重新 deploy 太慢，所以配置进 DO，后台存完立刻生效。
 *
 * 读不到 DO（它挂了、或者从没写过）就整份回落到 secret，功能不受影响。
 *
 * **线路的读法有两条路（R41③）**：新格式是 `routes` 那一个 JSON 数组；
 * 没有它的时候（线上刚部署完、DO 里还是 R39 存的那几个键）按老的
 * `base`/`key`/`model`/`proto`/`domestic` 拼出一条线路。
 * 这条回落不是过渡期的临时代码 —— 三个 secret（`CHAT_BASE`/`CHAT_KEY`/`CHAT_MODEL`）
 * 永远是「后台被清空时」的底座，它们只描述得了一条线路。
 */
async function loadCfg(env: Env): Promise<Cfg> {
  let over: Record<string, string> = {};
  try {
    const res = await cfgStub(env).fetch(new Request('https://chat.do/cfg'));
    if (res.ok) over = ((await res.json()) as { cfg?: Record<string, string> }).cfg ?? {};
  } catch {
    /* 读不到就用 secret */
  }

  const off = (over.off || env.CHAT_OFF || '') !== '';

  /* 老格式的那一条。`routes` 存在时它只当第 0 条的兜底值，不会被独立算进去 */
  const legacy: Route = {
    base: (over.base || env.CHAT_BASE || '').replace(/\/+$/, ''),
    key: over.key || env.CHAT_KEY || '',
    models: asModels(over.model || env.CHAT_MODEL || ''),
    proto: asProto(over.proto || env.CHAT_PROTO || 'openai'),
    domestic: (over.domestic || '') !== '',
  };

  let routes: Route[] = [];
  if (over.routes) {
    try {
      const raw = JSON.parse(over.routes) as unknown;
      if (Array.isArray(raw)) {
        routes = raw.slice(0, ROUTE_MAX).map((r) => {
          const o = (r ?? {}) as Record<string, unknown>;
          return {
            base: String(o.base ?? '').replace(/\/+$/, ''),
            key: String(o.key ?? ''),
            models: asModels(o.model),
            proto: asProto(o.proto),
            domestic: !!o.domestic,
          };
        });
      }
    } catch {
      /* 存坏了就当没有这一项 —— 下面会退回老格式那条，对话不会因为一个坏 JSON 停掉 */
    }
  }

  // 一条完整的都没有就用老格式那条（它也可能是空的，那时 `chat()` 直接走兜底）
  if (!routes.some((r) => r.base && r.key && r.models.length)) routes = [legacy];

  return { routes, off };
}

/** 往 DO 里追加一条。失败一律吞掉 —— 落库不该反过来把访客的对话弄坏 */
async function logMsg(
  env: Env,
  session: string,
  role: 'user' | 'ai',
  text: string,
  ip: string,
  model = '',
  /** 哪个浏览器窗口（R42）。空串是拿不到窗口号的老前端 */
  tab = ''
): Promise<void> {
  try {
    await stubOf(env, session).fetch(
      new Request('https://chat.do/append', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ role, text, ip, model, tab }),
      })
    );
  } catch {
    /* 存不进去也不能影响这一轮对话 */
  }
}

/**
 * 沉麟离开多久之后就不再让访客等（R41②）。
 *
 * 后台「聊天实时接管」那一页每 3 秒刷一次会话列表，每次刷新都会把「他还在」这个时刻
 * 记一笔。90 秒的容忍是给「切到别的浏览器标签看一眼」留的余地 ——
 * 那种情况下轮询会停（`document.hidden` 一到就停），但他人还在。
 *
 * 没有这一条的后果很具体：接管开着而他去睡了，之后每一个访客的每一句话都要先白等
 * 25 秒才轮到模型。这个开关因此是**可以放心一直开着**的。
 */
const AWAY_MS = 90000;

/**
 * 这个会话现在该由沉麟本人接吗（R41②）。两个条件都要成立：
 * 接管开着 **且** 他此刻人在后台。读不到一律当「不接管」——
 * 宁可让模型答，不让访客卡住。
 */
async function takenOver(env: Env, session: string): Promise<boolean> {
  try {
    const res = await cfgStub(env).fetch(
      new Request('https://chat.do/flag?id=' + encodeURIComponent(session))
    );
    if (!res.ok) return false;
    const d = (await res.json()) as { takeover?: unknown; seen?: unknown };
    if (!d.takeover) return false;
    return Date.now() - (Number(d.seen) || 0) < AWAY_MS;
  } catch {
    return false;
  }
}

/** 记一笔「他此刻在后台」。后台每次刷会话列表都会走这儿 */
async function noteSeen(env: Env): Promise<void> {
  try {
    await cfgStub(env).fetch(
      new Request('https://chat.do/cfg-set', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ seen: String(Date.now()) }),
      })
    );
  } catch {
    /* 记不上就当他不在 —— 那只是让接管这一次不生效，不会坏事 */
  }
}

/**
 * 挂起等沉麟本人回话（R41②）。返回空串＝他这一轮没回（超时），调用方退回模型生成。
 *
 * 不需要传游标：DO 那边的判据是「有没有比**最后一条访客消息**更新的人工回复」——
 * 访客这一句在调用前已经 `await` 落库了，所以那之后出现的人工回复必然是回它的。
 * 这样一来沉麟提前打好的回复也不会让访客白等（那条已经在库里，DO 立刻返回）。
 * 等待期间不烧 CPU（Workers 免费档限的是 10 ms **CPU** 时间，等 I/O 不计）。
 */
async function waitHuman(env: Env, session: string, tab: string): Promise<{ id: number; text: string }> {
  try {
    const res = await stubOf(env, session).fetch(
      new Request('https://chat.do/wait?tab=' + encodeURIComponent(tab))
    );
    if (!res.ok) return { id: 0, text: '' };
    const d = (await res.json()) as { id?: unknown; text?: unknown };
    return { id: Number(d.id) || 0, text: String(d.text ?? '') };
  } catch {
    return { id: 0, text: '' };
  }
}

/**
 * `GET /api/chat?tab=&after=` —— 访客侧的**主动接收**通道（R43）。
 *
 * 他报的是「接管后不能主动发送消息」。原因在架构里：R41／R42 的接管是应答式的
 * （访客问一句才有一条请求挂着），访客那边没有任何常驻通道，所以「没人发问时」
 * 沉麟打的字没地方送。这一条把「开着对话框」本身变成一条挂着的连接。
 *
 * 挂在 `GET /api/chat` 上而不是新开一条 `/api/chat/listen`：`wrangler.toml` 的
 * `run_worker_first` 列的是**精确路径** `"/api/chat"`，新路径不在里面就压根不进 Worker
 * （会被当静态资源，直接 404）。同一个路径换个方法，配置一行都不用动。
 */
async function listen(req: Request, env: Env): Promise<Response> {
  const p = new URL(req.url).searchParams;
  const tab = p.get('tab') ?? '';
  if (!TAB_RE.test(tab)) return fail(400, '窗口号不对');

  const ip = req.headers.get('cf-connecting-ip') ?? '';
  const session = ip ? await sessionOf(ip) : tab;

  const after = p.get('after') ?? '-1';
  try {
    const res = await stubOf(env, session).fetch(
      new Request(
        'https://chat.do/listen?tab=' + encodeURIComponent(tab) + '&after=' + encodeURIComponent(after)
      )
    );
    const d = (await res.json()) as { id?: unknown; text?: unknown };
    return json({ id: Number(d.id) || 0, text: String(d.text ?? '') }, CACHE.none);
  } catch {
    // 挂不上就回一个空的，前端会隔一会儿再试 —— 这条链路坏掉不该让对话框报错
    return json({ id: 0, text: '' }, CACHE.none);
  }
}

/**
 * 把「这一轮为什么没走通主路」记一笔到配置表（R39）。
 *
 * 为什么要落库而不是只 `console.warn`：`wrangler tail` 在本机这条链路上时常抓不到东西，
 * 而这类失败（上游 4xx、超时、抽不到内容）恰恰只有那一行原因有用。
 * 落进 cfg 表之后后台直接能看，不必再去翻日志。**不进响应体** —— 那是给访客的。
 */
async function noteWhy(env: Env, text: string): Promise<void> {
  try {
    await cfgStub(env).fetch(
      new Request('https://chat.do/cfg-set', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          lastwhy: new Date().toISOString().slice(5, 19).replace('T', ' ') + ' ｜ ' + text.slice(0, 600),
        }),
      })
    );
  } catch {
    /* 记不上就算了 */
  }
}

/**
 * 更新会话索引（R38，后台要能列出「有哪些人聊过」）。
 * DO 按会话分实例、彼此不可见，所以索引单独记在配置实例里。同样失败即吞。
 */
async function touchSession(
  env: Env,
  session: string,
  ip: string,
  model: string,
  add: number,
  /** 1 = 这个会话正等沉麟本人回话，0 = 不等了。不传就不动那一列（R41②） */
  wait?: number
): Promise<void> {
  try {
    await cfgStub(env).fetch(
      new Request('https://chat.do/touch', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ id: session, ip, model, add, wait }),
      })
    );
  } catch {
    /* 索引丢一条不影响对话，也不影响那条消息本身已经落库 */
  }
}

/** 取最近几轮当上下文。取不到就当没有历史，从头聊 —— 比整条请求失败好。
    `tab` 是窗口号（R42）：同一条会话里别人说的话不该串进这个人的上下文 */
async function loadHistory(
  env: Env,
  session: string,
  tab: string
): Promise<{ role: string; text: string }[]> {
  try {
    const res = await stubOf(env, session).fetch(
      new Request('https://chat.do/history?tab=' + encodeURIComponent(tab))
    );
    if (!res.ok) return [];
    const d = (await res.json()) as { items?: { role?: string; text?: string }[] };
    return Array.isArray(d.items)
      ? d.items.map((i) => ({ role: String(i.role ?? ''), text: String(i.text ?? '') }))
      : [];
  } catch {
    return [];
  }
}

/** 有些模型会裹一层 `<think>…</think>`。落库前剥掉（前端另有一套，那是给流式过程看的） */
const strip = (s: string) =>
  s
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    .replace(/<\/?think>/gi, '')
    .trim();

/**
 * 从一行 SSE 的 payload 里抽出这一小段增量文本。
 *
 * **先按配置的协议解析，抽不到再挨个嗅探**（R39）。为什么要嗅探这一层：
 * 协议是他在后台手选的，选错一档就会一个字都出不来 —— 而那种失败长得跟
 * 「模型不可用」一模一样，很难查。嗅探让配错协议最多损失一点点 CPU，不损失功能。
 * 顺带兜住 Workers AI 兜底那条路（`{"response":"字"}`，不属于任何一个协议）。
 */
function deltaOf(payload: string, shape: Shape): string {
  if (!payload || payload === '[DONE]') return '';
  try {
    const j = JSON.parse(payload) as Record<string, unknown>;

    const d = shape.delta(j);
    if (d) return d;

    for (const p of ['openai', 'anthropic', 'gemini', 'responses'] as Proto[]) {
      const alt = SHAPES[p].delta(j);
      if (alt) return alt;
    }
    // Workers AI 绑定
    return typeof j.response === 'string' ? j.response : '';
  } catch {
    /* 不是完整 JSON */
  }
  return '';
}

/** 把一段 SSE 文本切成整行，返回 [完整行数组, 剩下的半行] */
function lines(buf: string): [string[], string] {
  const parts = buf.split('\n');
  return [parts, parts.pop() ?? ''];
}

/**
 * 把 SSE 流读完并抽出正文。这一路是 `tee()` 出来的副本，
 * **客户端断开不影响它** —— 所以「访客问完就关页面」那种情况回答照样存得下来。
 */
async function collect(stream: ReadableStream, shape: Shape): Promise<string> {
  const reader = stream.getReader();
  const dec = new TextDecoder();
  let buf = '';
  let out = '';
  /** 全部原文，只在逐行扫不出东西时用来做非流式兜底（与 toSiteStream 同一个理由，R38） */
  let raw = '';

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      const chunk = dec.decode(value as Uint8Array, { stream: true });
      if (raw.length < 262144) raw += chunk;
      buf += chunk;
      const [rows, rest] = lines(buf);
      buf = rest;
      for (const row of rows) {
        if (!row.startsWith('data:')) continue;
        out += deltaOf(row.slice(5).trim(), shape);
      }
    }
  } catch {
    /* 上游断了：把已经收到的那部分存下来，半句也比丢掉好 */
  }

  // 上游没走 SSE：整段当一块 JSON 再试一次，否则这一轮落库会是空的
  if (!out) return onceOf(raw, shape);
  return strip(out);
}

/**
 * 上游**没有走 SSE**时的解析：整个响应体是一块普通 JSON。
 *
 * R38 实测出来的：他换到一个「可用」的模型之后，每一句回答都变成兜底文案
 * 「这个我答不上来。」—— 因为那个渠道对 `stream: true` 根本不流式返回，
 * 直接吐一整块 `{"choices":[{"message":{"content":"…"}}]}`。
 * 那里面**一行都不以 `data:` 开头**，逐行扫的解析器于是一个字都抽不出来。
 */
function onceOf(text: string, shape: Shape): string {
  try {
    const j = JSON.parse(text.trim()) as Record<string, unknown>;

    const one = shape.once(j);
    if (one) return strip(one);

    // 与 deltaOf 同一套嗅探：协议选错了也别让内容整段丢掉
    for (const p of ['openai', 'anthropic', 'gemini', 'responses'] as Proto[]) {
      const alt = SHAPES[p].once(j);
      if (alt) return strip(alt);
    }
    if (typeof j.response === 'string') return strip(j.response);
  } catch {
    /* 不是 JSON */
  }
  return '';
}

/**
 * 把上游 SSE 转成**本站自己的**格式：`data: {"d":"字"}`，收尾一条 `data: [DONE]`。
 *
 * 为什么要转而不是直通上游的字节：
 * - 前端只认一种格式，换上游不用动前端；
 * - **响应体里不留任何上游痕迹**（字段名、模型名、请求 id、usage 统计都会被丢掉）。
 *
 * **为什么手写 ReadableStream 而不用 `pipeThrough(new TransformStream(...))`**：
 * 上游中途断线或超时触发时，pipeThrough 会把错误往下游传播成一个未捕获的 rejection ——
 * 本机实测过一次，`wrangler dev` 直接崩在
 * `Uncaught TimeoutError: The operation was aborted due to timeout`，线上则会变成 500。
 * 手写之后错误在 `pull()` 里被吞掉，客户端收到一个正常的 `[DONE]`，
 * **已经吐出来的字都保留**，只是提前收尾。
 *
 * **兜住「上游其实没流式」这种情况**（R38）：一路累积原文，收尾时如果一个字都没发出去，
 * 就把整段当普通 JSON 再解析一次。不这么兜的话，那种渠道下每句回答都是空的。
 */
function toSiteStream(upstream: ReadableStream, shape: Shape): ReadableStream {
  const dec = new TextDecoder();
  const enc = new TextEncoder();
  const reader = upstream.getReader();
  let buf = '';
  /** 全部原文，只在「一个字都没发出」时用来做非流式兜底。上限防着异常大的响应 */
  let raw = '';
  let sent = 0;

  const bye = (ctrl: { enqueue(c: Uint8Array): void; close(): void }) => {
    // 没走 SSE 的渠道：整段当一块 JSON 再试一次
    if (!sent) {
      const once = onceOf(raw, shape);
      if (once) ctrl.enqueue(enc.encode(`data: ${JSON.stringify({ d: once })}\n\n`));
    }
    ctrl.enqueue(enc.encode('data: [DONE]\n\n'));
    ctrl.close();
  };

  return new ReadableStream({
    async pull(ctrl) {
      /**
       * ⚠ **必须在 pull 里循环读到「有东西可发」为止**（R39 的坑，查了很久）。
       *
       * 原来是「读一批 → 解析 → 有内容才 enqueue → 返回」。上游那些 chunk 里有大量
       * 不含正文的行（`{"delta":{"role":"assistant"}}`、心跳、空 `content`、
       * `finish_reason` 那条），碰上它们这一次 pull 就什么都没 enqueue ——
       * 而实测的结果是**之后 pull 再也不被调用**，客户端于是收到 0 个字。
       *
       * 证据是同一个流 tee 出来的另一路（落库用的 `collect`，写法是 `for(;;)` 一读到底）
       * 内容完整：库里存着「在蚌埠读书。具体学校就不说了。」，而客户端拿到的是空。
       * 两路用的是同一个 `deltaOf`，差别只在这个结构上。
       *
       * 所以这里自己兜住：一次 pull 内一直读，直到解析出内容（enqueue 后返回）
       * 或者上游结束（`bye`）。
       */
      try {
        for (;;) {
          const { done, value } = await reader.read();
          if (done) return bye(ctrl);

          const chunk = dec.decode(value as Uint8Array, { stream: true });
          if (raw.length < 262144) raw += chunk;
          buf += chunk;
          const [rows, rest] = lines(buf);
          buf = rest;

          let out = '';
          for (const row of rows) {
            if (!row.startsWith('data:')) continue;
            const d = deltaOf(row.slice(5).trim(), shape);
            if (d) out += `data: ${JSON.stringify({ d })}\n\n`;
          }

          if (out) {
            sent += out.length;
            ctrl.enqueue(enc.encode(out));
            return;
          }
          // 这一批全是心跳／空 delta／状态行 —— 继续读，别把 pull 让出去
        }
      } catch {
        bye(ctrl);
      }
    },
    cancel() {
      try {
        reader.cancel();
      } catch {
        /* 已经关了 */
      }
    },
  });
}

async function route(url: URL): Promise<Response> {
  const p = url.searchParams;

  switch (url.pathname.slice(API_PREFIX.length)) {
    case 'list': {
      const id = p.get('id') ?? '';
      // 白名单。少了这句，这就是个「任给 id 拉网易云歌单」的公开代理
      if (!isChartId(id)) return fail(400, '不认识这个榜单');
      const data = await upstream({ types: 'playlist', id, source: 'netease' });
      return json({ items: toList(data, LIST_MAX_N) }, CACHE.list);
    }

    case 'search': {
      const q = (p.get('q') ?? '').trim();
      if (!q) return fail(400, '要搜什么');
      // 用码点数而不是 .length：一个 emoji 是两个 UTF-16 单元，不该算两个字
      if ([...q].length > SEARCH_MAX_Q) return fail(400, `关键词最多 ${SEARCH_MAX_Q} 个字`);

      const n = clamp(Math.trunc(Number(p.get('n'))) || 12, 1, SEARCH_MAX_N);
      // 上游 count 是下限（count=10 会回 13 条），所以拿回来还得自己截到 n
      const data = await upstream({ types: 'search', count: String(n), pages: '1', name: q });
      return json({ items: toList(data, n) }, CACHE.search);
    }

    case 'url': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      if (!id || !source || !sign) return fail(400, '缺参数');

      const first = await getLink(id, source, sign);
      if (!first) return fail(502, '这首现在拿不到，换一首');

      // 没给歌名就没法择优 —— 原样返回，与择优上线前一模一样。
      // 榜单／搜索列表里点进来的都会带 name，不带的只有老前端
      const name = (p.get('name') ?? '').trim();
      if (!name) return json({ url: first }, CACHE.none);

      const artist = (p.get('artist') ?? '').trim();

      const bytes = await probeBytes(first);
      // 探不到大小就不折腾：既不能证明它是片段，而且连探头都失败了，
      // 后面那十几个请求大概也一样
      if (!bytes) return json({ url: first }, CACHE.none);
      if (bytes >= MIN_FULL_BYTES) return json({ url: first, bytes }, CACHE.none);

      const best = await pickBest(name, artist, bytes, `${source}:${id}`);
      const win = best ?? { url: first, bytes };

      const out: Record<string, unknown> = { url: win.url, bytes: win.bytes };
      // 换过源：前端可以据此知道播的不是它点的那条记录
      if (best) out.swapped = true;
      // 候选里最长的也还是偏短。不编造完整版，如实标出来让前端照实显示时长
      if (win.bytes < MIN_FULL_BYTES) out.short = true;
      return json(out, CACHE.none);
    }

    case 'lyric': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // song 是歌曲 id。lyric/pic 把它算进签名校验，漏了就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（歌词还要 song）');

      const data = await upstream({ types: 'lyric', id, source, song, sign });
      const lyric = pick(data, 'lyric');
      const tlyric = pick(data, 'tlyric');

      // 同上：错误信息也躺在 lyric 字段里。没有 [mm:ss 就一律当「这首没有词」，
      // 空字符串交给前端 —— 前端拿到空的就只是不显示歌词，不会把错误话当歌词唱出来
      if (!HAS_STAMP.test(lyric)) return json({ lyric: '', tlyric: '' }, CACHE.none);
      return json({ lyric, tlyric: HAS_STAMP.test(tlyric) ? tlyric : '' }, CACHE.lyric);
    }

    case 'pic': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // 与 lyric 同一个坑：pic 把歌曲 id 算进签名校验，漏了 song 就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（封面还要 song）');

      const data = await upstream({ types: 'pic', id, source, song, sign });
      const link = pick(data, 'url');
      // 「签名错误！」同样是 HTTP 200 + 合法 JSON + 对的字段名，所以看内容不看形状。
      // 前端拿到 502 就一直用文字标签 —— 没封面不影响听
      if (!link.startsWith('https://')) return fail(502, '这首没有封面');
      // 字节不经过 Worker：直链自带 `acao: *` 与一年的缓存，浏览器直接去 p3.music.126.net 拉
      return json({ url: link }, CACHE.pic);
    }

    default:
      return fail(404, '没有这个接口');
  }
}

/**
 * 等上游**响应头**的上限。拿到头之后就不限了 —— 用 `AbortSignal.timeout(总时长)`
 * 会把正常的长回答一起掐断。
 *
 * **30 秒不是随便定的**（R39 的坑）：一开始给 12 秒，理由是「不通的时候 Cloudflare 侧
 * 要 30 秒才放弃，别让访客干等」。结果换到一个真能用的上游之后，对话仍然一个字都不出 ——
 * 而后台的非流式测试是好的。原因是**很多上游要先把 prompt 读完、开始生成，才发响应头**：
 * 系统提示词有一万多 token 时那一步就要十几秒，12 秒正好卡在中间，
 * 于是每次都 abort 掉主路、掉进兜底，表现成「所有回答都一样」。
 *
 * 首字延迟因此与提示词长度直接相关 —— 这是「精简提示词」除了省钱之外的第二个理由。
 */
const HEAD_TIMEOUT_MS = 30000;

/** 兜底（Workers AI 绑定）也要有上限。它 hang 住时同样不能让访客干等 */
const BIND_TIMEOUT_MS = 20000;

/** 探针（后台最小测试）用的上限。那是他自己在看，愿意多等一会儿换一个明确结论 */
const PROBE_TIMEOUT_MS = 30000;

/**
 * 可达性探测的上限（R41③）。比 `PROBE_TIMEOUT_MS` 短得多，因为它问的是另一个问题：
 * **「能不能拿到响应头」**，而不是「能不能生成一段回答」。通的路径实测都在 0.5–4 秒
 * （本机打十四家国内端点，最慢的讯飞 5.8 秒），10 秒还没有头就可以判定为不通了。
 * 短一点还有一个好处：一次探测要打目标 + 对照两个地址，不通时他只用等 10 秒不是 30 秒。
 */
const REACH_TIMEOUT_MS = 10000;

/**
 * 打上游时带的请求头。除了鉴权与 content-type，其余是一个**真实 OpenAI 客户端**
 * （`openai-node` SDK）会发的那一套 —— 裸 fetch 只带两个头，在按客户端做路由或
 * 限流的网关那儿容易被区别对待。这些头不含任何本站信息，也不含访客信息。
 */
const CLIENT_HEADERS: Record<string, string> = {
  accept: 'text/event-stream',
  'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
  'user-agent': 'OpenAI/JS 4.104.0',
  'x-stainless-lang': 'js',
  'x-stainless-package-version': '4.104.0',
  'x-stainless-os': 'Windows',
  'x-stainless-arch': 'x64',
  'x-stainless-runtime': 'node',
  'x-stainless-runtime-version': 'v22.12.0',
  'x-stainless-retry-count': '0',
};

/**
 * 主路。地址、模型、密钥、**请求格式**全部来自配置 ——
 * 这个函数里没有任何一个值是写在仓库里的。
 *
 * 抛出的 Error 的 message 只有我自己写的字 + HTTP 状态码，
 * **上游响应体一个字都不外泄**（它可能带自己的域名、模型名与报错细节）。
 */
async function askUpstream(
  route: Route,
  model: string,
  system: string,
  turns: Turn[]
): Promise<ReadableStream> {
  const shape = SHAPES[route.proto];

  /* 只给「建连 + 拿到响应头」设超时，拿到之后 `clearTimeout` —— 流式读取不受限。
     abort 会真正取消这次 fetch，不是只放弃等待。 */
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), HEAD_TIMEOUT_MS);

  let res: Response;
  try {
    res = await fetch(shape.url(route.base, model, route.key), {
      method: 'POST',
      headers: {
        ...CLIENT_HEADERS,
        ...shape.headers(route.key),
        'content-type': 'application/json',
      },
      body: JSON.stringify(
        shape.body({
          model,
          system,
          turns,
          max: MAX_TOKENS,
          temp: TEMPERATURE,
          stream: true,
        })
      ),
      signal: ac.signal,
    });
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok || !res.body) throw new Error('上游 HTTP ' + res.status);
  return res.body;
}

/** 兜底：Workers AI 绑定。零密钥、零第三方，主路缺配置或这一次失败时走它 */
async function askBinding(env: Env, system: string, turns: Turn[]): Promise<ReadableStream> {
  // Workers AI 的绑定就是 OpenAI 那套形状，直接借 openai 的 body
  const messages = [{ role: 'system', content: system }, ...turns];
  /* `env.AI.run` 不收 AbortSignal，所以只能 race。**race 不会取消底层请求** ——
     它挂住的话那个 promise 会一直悬着（Worker 生命周期结束时才收），
     但至少访客不用陪它等。线上实测这个绑定在本账号上就是会挂（R37）。 */
  const out = await Promise.race([
    env.AI.run(FALLBACK_MODEL, {
      messages,
      stream: true,
      max_tokens: MAX_TOKENS,
      temperature: TEMPERATURE,
    }),
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('兜底 ' + BIND_TIMEOUT_MS + 'ms 没响应')), BIND_TIMEOUT_MS)
    ),
  ]);

  if (!(out instanceof ReadableStream)) throw new Error('绑定返回的不是流');
  return out;
}

/**
 * 把一段现成的文字包成本站自己的 SSE（R41②，人工接管时用）。
 *
 * 切成小块逐段发而不是一次吐完：前端那套渲染是按增量追加的，一次一大块会「啪」地
 * 整段出现，和模型回答时的逐字长得不一样 —— 访客不该从节奏上看出这一句是人打的。
 * 24 个字符一块、每块间隔 40 ms，一句两百字的话大约 0.35 秒出完。
 *
 * 收尾多发一条 `data: {"seen":<id>}`（R43）：这一句同时也躺在库里，而访客侧现在还有一条
 * `/listen` 长轮询在收人工消息 —— 不把游标推过去，同一句话会**再从 listen 里出来一次**。
 * 前端拿到 `seen` 就把游标推到这条的 id。
 */
function textStream(text: string, seen = 0): ReadableStream {
  const enc = new TextEncoder();
  const chars = [...text];
  let i = 0;

  return new ReadableStream({
    async pull(ctrl) {
      if (i >= chars.length) {
        if (seen) ctrl.enqueue(enc.encode(`data: ${JSON.stringify({ seen })}\n\n`));
        ctrl.enqueue(enc.encode('data: [DONE]\n\n'));
        ctrl.close();
        return;
      }
      const piece = chars.slice(i, i + 24).join('');
      i += 24;
      ctrl.enqueue(enc.encode(`data: ${JSON.stringify({ d: piece })}\n\n`));
      if (i < chars.length) await new Promise((r) => setTimeout(r, 40));
    },
  });
}

/** 流式响应的头。三处共用（模型、人工接管、兜底），漏掉 no-store 就会把一次问答缓存给下一个人 */
const STREAM_HEADERS = {
  'content-type': 'text/event-stream; charset=utf-8',
  'cache-control': 'no-store',
  'x-robots-tag': 'noindex',
} as const;

/**
 * `POST /api/chat` —— 一句话进，一段流出。
 *
 * 失败一律返回 JSON + 一句中文人话，前端照原样显示给访客：
 * 这是唯一会被访客读到的错误文案，别在里面漏上游细节。
 */
async function chat(req: Request, env: Env, ctx: Ctx): Promise<Response> {
  if (req.method !== 'POST') return fail(405, '这个接口只接 POST');

  const cfg = await loadCfg(env);

  // 保险丝（R32：护栏先不设，但要有关停开关）。后台那个开关也走这一条
  if (cfg.off) return fail(503, '今天先不聊了，回头再来');

  let body: { session?: unknown; tab?: unknown; message?: unknown };
  try {
    body = (await req.json()) as typeof body;
  } catch {
    return fail(400, '请求体不是 JSON');
  }

  const message = (typeof body.message === 'string' ? body.message : '').trim();
  if (!message) return fail(400, '说点什么');
  // 码点数而不是 .length：一个 emoji 是两个 UTF-16 单元，不该算两个字
  if ([...message].length > MSG_MAX) return fail(400, `一次最多 ${MSG_MAX} 个字`);

  let kb: KbItem[];
  try {
    kb = await loadKb(env, req.url);
  } catch {
    return fail(503, '知识库这会儿读不出来，等一下再问');
  }

  // R32 他定了要存 IP。这是 Cloudflare 注入的头，访客改不了
  const ip = req.headers.get('cf-connecting-ip') ?? '';

  /* ---- 会话号与窗口号（R42：「同一 IP 使用相同会话」）---------------------
     **会话号一律在服务端按 IP 算**，前端传什么都不采信 —— 前端不知道自己的 IP，
     而且它传上来的值本来就是「一个标签页一份、关掉就换新的」（见 `sessionOf` 的注释）。

     `tab` 是那个 uuid 现在的用途：窗口号。老前端（边缘缓存里最多还能活 7 天的那些页面）
     发的是 `session` 字段，把它当窗口号收下 —— 形状一样，语义正好也对得上
     「一个标签页一份」。

     **拿不到 IP 时**（本机 `curl` 没有 `cf-connecting-ip`）退回用窗口号当会话号，
     与 R41 的行为一致；本机验收因此不受影响。 */
  const given = typeof body.tab === 'string' ? body.tab : typeof body.session === 'string' ? body.session : '';
  const tab = TAB_RE.test(given) ? given : '';
  if (!tab) return fail(400, '窗口号不对');

  const session = ip ? await sessionOf(ip) : tab;
  if (!SESSION_RE.test(session)) return fail(400, '会话号不对');

  /* ---- 人工接管（R41②）--------------------------------------------------
     沉麟在后台把这个会话标成「我自己接」时，这一轮不调模型：访客那句话落库之后
     挂起等他打字（最多 25 秒），他一按发送就把原话流给访客。

     三个决定：
     ① 访客那条必须 **await** 落库，不能用 waitUntil —— 后台要立刻看到这句话才有得可回，
        而且 DO 那边判断「有没有新的人工回复」用的就是「最后一条访客消息」这个锚点；
     ② 超时之后**退回模型**，不是回一句「他不在」。访客不知道有接管这回事，
        他等了 25 秒该拿到一个回答；
     ③ 访客侧看不出区别 —— 同一条 SSE 格式、同样逐段出字（见 `textStream`）。 */
  if (await takenOver(env, session)) {
    await logMsg(env, session, 'user', message, ip, '', tab);
    await touchSession(env, session, ip, '', 1, 1);

    const human = await waitHuman(env, session, tab);
    await touchSession(env, session, ip, '', 0, 0);

    // 那句话在 DO 的 `/reply` 里已经落库了，这儿只负责送出去，不重复写一遍
    if (human.text)
      return new Response(textStream(human.text, human.id), { headers: STREAM_HEADERS });
    /* 他没接上 —— 往下走模型那条路。访客这句已经在库里了，下面靠 `dup` 认出来，
       不会把同一句话问两遍 */
  }

  const history = await loadHistory(env, session, tab);

  /* system 与对话分开传：四个协议里有三个把 system 放在 body 顶层
     （Anthropic 的 `system`、Responses 的 `instructions`、Gemini 的 `systemInstruction`），
     只有 OpenAI 兼容那套塞在 messages 里。拼装的活交给 `data/proto.ts`。 */
  /* ⚠ **知识库全带，不做检索**（R39 试过又退回来了）。
     一度改成「按字面重叠挑最相关的 8 条」，`prompt_tokens` 从 14722 降到 9162（省 38%）。
     但线上三轮实测立刻暴露代价：第二轮问工具时 `where-i-live` 没被挑中，
     分身看到自己上一句说过「蚌埠」而当前依据里没有，于是**当场自我否认** ——
     「先纠一下上一句：地点我不该说，那不是他写过的东西」。第三轮又否认了一次工具那段。
     一个会怀疑自己说过的话的分身，比多花 38% 的 token 糟得多。

     真要再省，方向是**把条目本身写短**（现在平均四百多字），不是随机抽几条 ——
     那是他的内容，得他自己动手。`pickKb` 留在 `data/chat.ts` 里没删，
     等哪天条目多到装不下（六十条以上）再启用，那时漏检的代价才小于装不下的代价。 */
  const system = buildSystem(kb);
  const past: Turn[] = history.map((h) => ({
    role: (h.role === 'user' ? 'user' : 'assistant') as 'user' | 'assistant',
    content: h.text,
  }));
  /* 接管超时那条路上访客这句已经在历史里了（上面 await 落库过），再追加一次就变成
     「同一句话问了两遍」。判据用「最后一条历史是不是逐字相同的访客消息」而不是传一个
     布尔值进来 —— 将来谁改了上面的顺序，这一条也不会悄悄坏掉。 */
  const dup =
    past.length > 0 &&
    past[past.length - 1].role === 'user' &&
    past[past.length - 1].content === message;
  const turns: Turn[] = dup ? past : [...past, { role: 'user' as const, content: message }];

  // 访客那条先落库：模型这一轮失败了，他说过的话也还在
  if (!dup) ctx.waitUntil(logMsg(env, session, 'user', message, ip, '', tab));

  /* 路径顺序：**每条线路的每个候选模型**（R41③ 起线路也可以有多条）→ Workers AI 兜底。
     失败原因只进 Worker 日志与 `lastwhy`，**不进响应体**。

     为什么要多候选：这家上游的模型可用性会漂移 —— 本机实测同一个模型 20 分钟前还好，
     再调就返「没有可用通道」。写两三个候选，第一个挂了自动换下一个，
     比直接掉到兜底（免费档 196 次/天）划算。线路那一层是同一个道理、粒度更大：
     国内服务商从境外边缘打不通时，第二条线路顶上，功能不停。 */
  const usable = cfg.routes.filter((r) => r.base && r.key && r.models.length);
  if (!usable.length) {
    /* 一条完整线路都没有就整段主路不走。线上如果 secret 忘配、或者后台把它清空了，
       这一行是唯一能看出来的地方（只报有无，不报值） */
    console.warn(
      '没有可用线路，直接走兜底 —— 共 ' +
        cfg.routes.length +
        ' 条：' +
        cfg.routes
          .map(
            (r, i) =>
              `#${i + 1} base:${r.base ? '有' : '无'} key:${r.key ? '有' : '无'} model:${r.models.length}`
          )
          .join('，')
    );
  }

  let raw: ReadableStream | null = null;
  /** 这一轮真正出字的是谁 —— 落库与后台的「模型使用」都靠它 */
  let used = '';
  /**
   * 出字那条线路的协议形状。**不能统一用第一条线路的** —— 三条线路可以各配不同协议，
   * 解析器拿错协议就一个字都抽不出来（R39 那个坑的加强版：那次是选错协议，
   * 这次会是「换了线路但还拿着上一条的解析器」）。
   */
  let shape = SHAPES[usable[0]?.proto ?? 'openai'];
  const why: string[] = [];

  for (const route of usable) {
    for (const m of route.models) {
      try {
        raw = await askUpstream(route, m, system, turns);
        used = m;
        shape = SHAPES[route.proto];
        break;
      } catch (e) {
        why.push(
          '线路 ' +
            route.proto +
            (route.domestic ? '·国内' : '') +
            ' 的 ' +
            m +
            '：' +
            (e instanceof Error ? e.message : String(e))
        );
      }
    }
    if (raw) break;
  }

  if (!raw) {
    try {
      raw = await askBinding(env, system, turns);
      used = FALLBACK_MODEL;
      /* 绑定回的是 `{"response":"字"}`，四个协议都不认它 ——
         `deltaOf`／`onceOf` 里各有一条专门的兜底分支接着，所以这儿给哪个 shape 都行，
         给 openai 是因为它的嗅探顺序最短 */
      shape = SHAPES.openai;
    } catch (e) {
      /* Workers AI 免费额度用完也走这儿（官方 pricing：超额后该类型操作直接报错，
         不自动计费也不降级） */
      why.push('兜底：' + (e instanceof Error ? e.message : String(e)));
    }
  }

  if (!raw) {
    console.error('全部线路都没通 —— ' + why.join('｜'));
    ctx.waitUntil(noteWhy(env, '全部线路都没通 ｜ ' + why.join(' ｜ ')));
    // 这一轮虽然没答上来，访客那句话已经落库了，索引也要跟上（不然后台看不到这次来访）
    ctx.waitUntil(touchSession(env, session, ip, '', dup ? 0 : 1));
    return fail(502, '我这会儿答不上来，等一下再问');
  }

  if (why.length) {
    console.warn('前面的线路没走通，最后用的是 ' + used + ' —— ' + why.join('｜'));
    ctx.waitUntil(noteWhy(env, '最后用的是 ' + used + ' ｜ ' + why.join(' ｜ ')));
  }

  const [toClient, toLog] = raw.tee();
  ctx.waitUntil(
    collect(toLog, shape).then(async (text) => {
      if (text) await logMsg(env, session, 'ai', text, '', used, tab);
      // 一个字都没抽出来：把它也记一笔，否则这种失败在后台完全看不见
      else await noteWhy(env, '出字 0 ｜ 用的是 ' + (used || '（无）'));
      // 一问一答算两条；答没出来就只算问的那一条（接管超时那条路上问的那条已经算过了）
      await touchSession(env, session, ip, used, (dup ? 0 : 1) + (text ? 1 : 0));
    })
  );

  return new Response(toSiteStream(toClient, shape), { headers: STREAM_HEADERS });
}

/* ==========================================================================
   后台 `/admin` —— R20② 那把锁（方案 B：自建口令 + 签名 cookie）＋ 模型配置台

   他要的三件事：藏起来、能实时改模型配置、能最小文本测试。
   - **藏起来**：不在任何导航里，靠登录保护。**不靠地址难猜** —— 那不是安全边界。
   - **实时改**：配置存 DO（`loadCfg`），存完下一次对话立刻生效，不用 deploy。
   - **最小测试**：`/api/admin/test` 用非流式、`max_tokens: 48` 打一次，
     把每个候选的耗时、状态码、正文、思考字数都报回来。上游漂移时这一页是唯一的确诊工具。

   `/admin` 那一页**照旧是公开可取的静态 HTML**（`public/_headers` 给 HTML 配了边缘缓存，
   而边缘缓存是共享的 —— 登录态一旦进 HTML 就会把一个人的页面发给另一个人）。
   所以那页里一个字的敏感内容都没有，全部由登录后的 fetch 填。
   ========================================================================== */

const ADMIN_PREFIX = '/api/admin/';

/** 登录有效期。七天 —— 够他隔几天回来看一次不用重新输 */
const SESSION_DAYS = 7;

const COOKIE = 'adm';

const enc = new TextEncoder();

const b64 = (buf: ArrayBuffer) => {
  let s = '';
  for (const b of new Uint8Array(buf)) s += String.fromCharCode(b);
  return btoa(s);
};

const unb64 = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

/**
 * 恒定时间比较。长度不同直接返回 false —— 长度本身不是秘密，
 * 而按位比完整个串才是重点（避免用响应时间猜出前缀）。
 */
function timingEq(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function pbkdf2(pass: string, salt: BufferSource, iterations: number): Promise<string> {
  const key = await crypto.subtle.importKey('raw', enc.encode(pass), 'PBKDF2', false, [
    'deriveBits',
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt, iterations },
    key,
    256
  );
  return b64(bits);
}

/** `ADMIN_HASH` = `pbkdf2$<迭代数>$<saltB64>$<hashB64>`。格式不对一律当「口令错」 */
async function passOk(env: Env, pass: string): Promise<boolean> {
  const parts = (env.ADMIN_HASH ?? '').split('$');
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false;

  const iter = Number(parts[1]);
  // 上限是为了挡「有人把迭代数写成一亿」—— 那会把每次登录都变成一次 CPU 超时
  if (!Number.isFinite(iter) || iter < 1000 || iter > 200000) return false;

  try {
    return timingEq(await pbkdf2(pass, unb64(parts[2]), iter), parts[3]);
  } catch {
    return false;
  }
}

async function hmac(secret: string, payload: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  return b64(await crypto.subtle.sign('HMAC', key, enc.encode(payload)));
}

/**
 * cookie 值 = `<过期毫秒>.<签名>`。**无状态** —— 不需要 KV、不需要记会话，
 * 所以 R6 那条「不落库」在鉴权这一侧一个字都不用动。
 */
const mintCookie = async (env: Env) => {
  const exp = String(Date.now() + SESSION_DAYS * 86400_000);
  return `${exp}.${await hmac(env.ADMIN_SECRET ?? '', exp)}`;
};

async function cookieOk(env: Env, req: Request): Promise<boolean> {
  // 两样 secret 缺一样就当没登录 —— 这把锁宁可锁死也不能开着
  if (!env.ADMIN_SECRET || !env.ADMIN_HASH) return false;

  const raw = (req.headers.get('cookie') ?? '')
    .split(';')
    .map((s) => s.trim())
    .find((s) => s.startsWith(COOKIE + '='));
  if (!raw) return false;

  const val = raw.slice(COOKIE.length + 1);
  const dot = val.indexOf('.');
  if (dot < 1) return false;

  const exp = val.slice(0, dot);
  const sig = val.slice(dot + 1);

  // 过期时间在签名覆盖范围内，所以把它改远一定失配
  if (!timingEq(await hmac(env.ADMIN_SECRET, exp), sig)) return false;
  return Number(exp) > Date.now();
}

const setCookie = (value: string, maxAge: number) =>
  `${COOKIE}=${value}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${maxAge}`;

/** 带 Set-Cookie 的 JSON 响应 */
const cookieJson = (data: unknown, cookie: string) =>
  new Response(JSON.stringify(data), {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'no-store',
      'x-robots-tag': 'noindex',
      'set-cookie': cookie,
    },
  });

/**
 * 打一次上游，只为回答「这个模型现在能不能用」。
 * 非流式、一句最短的中文 —— 一次测试的成本可以忽略。
 *
 * `max_tokens` 给 300 而不是几十：**会思考的模型会先花掉一大截预算**。
 * 本机实测过一次误报 —— 给 48 的时候某个候选 HTTP 200、思考 217 字、正文一个字没有，
 * 于是被判成「不能用」，而它在真实对话（上限 700）里是好的。
 *
 * 返回里带 `think`（`reasoning_content` 的字数）就是为了让这种情况一眼能认出来：
 * `ok` 是 false 而 `think` 很大 = 预算被思考吃光，不是模型坏了。
 */
const PROBE_MAX_TOKENS = 300;

/**
 * 「这个模型认不认角色设定」的判据。
 *
 * R37 实测出的一个硬事实：**有的模型收到了 system 也照样不认**。
 * 那次是 `prompt_tokens` 4125（24 条知识库确实送到了），可它仍然回
 * 「我是 XX，由 XX 公司创造的 AI 助手，我可以帮你生成图片…」——
 * 身份被写进了权重里，提示词怎么加强都改不动（加了最强的一段身份约束后重测，一字不改）。
 *
 * 所以测试台要能一眼看出这件事：回答里出现任何厂商名、模型名、或者「AI 助手」
 * 这类自我介绍，就是不听话，这个模型不能拿来当分身。
 */
const NOT_OBEDIENT =
  /deepseek|chatgpt|openai|gpt-[0-9]|qwen|通义|千问|智谱|glm|kimi|月之暗面|深度求索|minimax|海螺|claude|anthropic|gemini|文心|讯飞|星火|豆包|step-?[0-9]|ai\s*助手|人工智能助手|大模型|语言模型/i;

async function probe(route: Route, model: string, kb: KbItem[]): Promise<Record<string, unknown>> {
  const shape = SHAPES[route.proto];
  const t0 = Date.now();

  try {
    const res = await fetch(onceUrl(route.proto, shape.url(route.base, model, route.key)), {
      method: 'POST',
      headers: {
        ...CLIENT_HEADERS,
        ...shape.headers(route.key),
        accept: 'application/json',
        'content-type': 'application/json',
      },
      /* **带上真实的系统提示词**：他换了模型之后报「明显没连接到知识库」，
         而光问「说三个字」是查不出这件事的。台账 R34 记过一个模型 `prompt_tokens`
         只有 8 —— 它把 system 整个丢了。送 system 再看回来的 token 数就能定性。 */
      body: JSON.stringify(
        shape.body({
          model,
          // 与真实对话一致：全带。报出来的 prompt_tokens 就是真实开销
          system: buildSystem(kb),
          turns: [{ role: 'user', content: '你是谁？' }],
          max: PROBE_MAX_TOKENS,
          temp: TEMPERATURE,
          stream: false,
        })
      ),
      signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
    });

    const ms = Date.now() - t0;
    const body = await res.text();

    // 上游的错误原文只回给**已登录的他自己**，这是诊断必需的（截断到 200 字）
    if (!res.ok) return { model, ok: false, ms, status: res.status, error: body.slice(0, 200) };

    let j: Record<string, unknown>;
    try {
      j = JSON.parse(body) as Record<string, unknown>;
    } catch {
      return { model, ok: false, ms, status: res.status, error: '上游返回的不是 JSON' };
    }

    const out = onceOf(body, shape);
    const think = String(
      (j.choices as { message?: { reasoning_content?: unknown } }[] | undefined)?.[0]?.message
        ?.reasoning_content ?? ''
    ).length;

    return {
      model,
      ok: !!out,
      ms,
      status: res.status,
      text: out.slice(0, 160),
      think,
      promptTokens: tokensOf(j),
      /* 「能连通」与「能当分身」是两件事。只有两者都成立才算可用 */
      obedient: !!out && !NOT_OBEDIENT.test(out),
    };
  } catch (e) {
    return {
      model,
      ok: false,
      ms: Date.now() - t0,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

/**
 * 送进去的提示词有多少 token —— 「知识库到没到」的判据。三个协议放在三个地方：
 * OpenAI 系 `usage.prompt_tokens`、Anthropic `usage.input_tokens`、
 * Gemini `usageMetadata.promptTokenCount`。取不到就返回 null（不猜）。
 */
function tokensOf(j: Record<string, unknown>): number | null {
  const u = j.usage as { prompt_tokens?: unknown; input_tokens?: unknown } | undefined;
  const g = j.usageMetadata as { promptTokenCount?: unknown } | undefined;
  for (const v of [u?.prompt_tokens, u?.input_tokens, g?.promptTokenCount]) {
    const n = Number(v);
    if (Number.isFinite(n) && n > 0) return n;
  }
  return null;
}

/**
 * `/api/admin/*`。五条：login / logout / state / save / test。
 *
 * 失败文案一律同一句「进不去」，**不区分「口令错」「没给口令」「还没设口令」** ——
 * 区分开就等于告诉对面「这个账号存在，只是密码不对」。
 */
async function admin(req: Request, env: Env): Promise<Response> {
  const path = new URL(req.url).pathname.slice(ADMIN_PREFIX.length);
  const ready = !!(env.ADMIN_HASH && env.ADMIN_SECRET);

  if (path === 'login') {
    if (req.method !== 'POST') return fail(405, '只接 POST');
    let pass = '';
    try {
      pass = String(((await req.json()) as { pass?: unknown }).pass ?? '');
    } catch {
      /* 请求体不对就当空口令，走同一条失败路径 */
    }
    if (!ready || !(await passOk(env, pass))) {
      /* 失败固定等一秒才回。**这是给短口令买的时间**：默认那个口令只有三位，
         不拖一下的话单线程几十秒就能穷举完。
         等待不计入 Workers 的 CPU 时间（10 ms/请求那条限制只算 CPU），所以这一秒是免费的。
         挡不住并发爆破 —— 真要挡得加失败计数与锁定，那需要状态，等他想换长口令时再说。

         ⚠ 口令的**值**一个字都不许出现在这个仓库里（它是公开的）。要看当前口令，
         去本机 `.dev.vars`（已被 .gitignore 排除）。 */
      await new Promise((r) => setTimeout(r, 1000));
      return json({ ok: false, error: '进不去' }, CACHE.none, 401);
    }
    return cookieJson({ ok: true }, setCookie(await mintCookie(env), SESSION_DAYS * 86400));
  }

  if (path === 'logout') return cookieJson({ ok: true }, setCookie('', 0));

  const logged = await cookieOk(env, req);

  /* 这一条**未登录也能打**，因为登录框要靠它知道「口令设了没有」——
     但未登录时除了这两个布尔值，一个字的配置都不返回 */
  if (path === 'state') {
    if (!logged) return json({ logged: false, ready }, CACHE.none);
    const cfg = await loadCfg(env);
    return json(
      {
        logged: true,
        ready,
        /* 线路数组。**密钥永不回显**，只报有无 —— 后台那个输入框留空就是「不改」，
           填了才覆盖。R41 起是数组；前端仍然按下标一条条渲染，第一条就是主线 */
        routes: cfg.routes.map((r) => ({
          base: r.base,
          model: r.models.join(', '),
          hasKey: !!r.key,
          proto: r.proto,
          domestic: r.domestic,
        })),
        off: cfg.off,
        lastWhy: await lastWhy(env),
        fallback: FALLBACK_MODEL,
        routeMax: ROUTE_MAX,
      },
      CACHE.none
    );
  }

  if (!logged) return json({ ok: false, error: '进不去' }, CACHE.none, 401);

  /* ---- 对话记录（R38 他要的「查看对话记录详情」）------------------------
     这一段都是 GET，所以在这儿处理，不进 adminWrite（那边只接 POST）。
     它们会返回访客的 IP 与原文，**只有登录后能打**。 */

  /** 会话列表。最近活跃的排前面。R41 起每条还带「接管中／有人在等」两个标记 */
  if (path === 'sessions') {
    try {
      /* 顺手记一笔「他此刻在后台」—— 接管要靠它判断「人在不在」（见 `takenOver`）。
         这一条接口是后台每 3 秒必打的那一条，挂在这儿不必再多一个心跳接口。
         `await` 而不是丢在后台：它就是一次本地 DO 调用，几毫秒 */
      await noteSeen(env);
      const res = await cfgStub(env).fetch(
        new Request('https://chat.do/sessions?n=' + (new URL(req.url).searchParams.get('n') ?? '60'))
      );
      const d = (await res.json()) as { items?: unknown };
      return json({ ok: true, items: Array.isArray(d.items) ? d.items : [] }, CACHE.none);
    } catch {
      return fail(502, '会话索引读不出来');
    }
  }

  /**
   * 某一个会话的消息。`after` 给「实时接管」那一页的轮询用：
   * 带上上一轮拿到的最后一条 id，这一轮只回比它更新的几条，不必每 1.5 秒搬四百条。
   */
  if (path === 'log') {
    const p = new URL(req.url).searchParams;
    const id = p.get('session') ?? '';
    if (!SESSION_RE.test(id)) return fail(400, '会话号不对');
    const after = Math.max(0, Math.trunc(Number(p.get('after'))) || 0);
    try {
      const res = await stubOf(env, id).fetch(
        new Request('https://chat.do/all?n=400&after=' + after)
      );
      const d = (await res.json()) as { items?: unknown; last?: unknown };
      return json(
        {
          ok: true,
          items: Array.isArray(d.items) ? d.items : [],
          last: Number(d.last) || after,
        },
        CACHE.none
      );
    } catch {
      return fail(502, '这个会话读不出来');
    }
  }

  /** 顶栏那几个实时数字（R41②）。所有 tab 的角标都从这一条来，一次问完 */
  if (path === 'stat') {
    try {
      const res = await cfgStub(env).fetch(new Request('https://chat.do/stat'));
      const d = (await res.json()) as Record<string, unknown>;
      return json({ ok: true, ...d, content: CONTENT.length }, CACHE.none);
    } catch {
      return fail(502, '数字读不出来');
    }
  }

  /**
   * 仓库里现有内容的原文（R41②「文章编辑」与「图库管理」）。
   *
   * 来自 `src/data/content.generated.ts` —— **编译进 Worker 包，不是静态资源**。
   * 那个文件为什么不做成 `/admin-content.json`，理由写在 `scripts/gen-content.mjs` 顶部：
   * `dist/` 里的东西全是公开可取的，而 `draft: true` 的正文恰恰是他还没决定要不要公开的。
   *
   * 默认只回目录（不含正文）：33 个文件的正文加起来 39 KB，列表页用不着。
   * 带 `?path=` 才回那一份的 frontmatter 与正文。
   */
  if (path === 'content') {
    const p = new URL(req.url).searchParams;
    const want = p.get('path') ?? '';
    if (want) {
      const one = CONTENT.find((c) => c.path === want);
      if (!one) return fail(404, '没有这个文件');
      return json({ ok: true, item: one }, CACHE.none);
    }
    /* `?coll=` 回**整个集合的全文**（含 frontmatter 与正文）。图库管理要靠它 ——
       一个相册的封面、alt、图片数全在 frontmatter 里，一条条 `?path=` 拉是
       N 次往返。全站正文加起来 39 KB，一次发完比来回问便宜。 */
    const coll = p.get('coll') ?? '';
    if (coll) {
      return json({ ok: true, items: CONTENT.filter((c) => c.coll === coll) }, CACHE.none);
    }
    return json(
      {
        ok: true,
        items: CONTENT.map((c) => ({
          coll: c.coll,
          slug: c.slug,
          path: c.path,
          title: c.title,
          draft: c.draft,
          pubDate: c.pubDate,
          chars: [...c.body].length,
        })),
      },
      CACHE.none
    );
  }

  /** 后台草稿列表（R41②）。不含正文，点开才拉 */
  if (path === 'drafts') {
    try {
      const res = await cfgStub(env).fetch(new Request('https://chat.do/drafts'));
      const d = (await res.json()) as { items?: unknown };
      return json({ ok: true, items: Array.isArray(d.items) ? d.items : [] }, CACHE.none);
    } catch {
      return fail(502, '草稿读不出来');
    }
  }

  /** 一份草稿的全文 */
  if (path === 'draft') {
    const id = new URL(req.url).searchParams.get('id') ?? '';
    if (!id) return fail(400, '缺 id');
    try {
      const res = await cfgStub(env).fetch(
        new Request('https://chat.do/draft?id=' + encodeURIComponent(id))
      );
      if (!res.ok) return fail(404, '没有这份草稿');
      const d = (await res.json()) as { item?: unknown };
      return json({ ok: true, item: d.item ?? null }, CACHE.none);
    } catch {
      return fail(502, '草稿读不出来');
    }
  }

  /**
   * 能不能连上这家服务商（R41③）—— 他那句「我必须能使用国内的服务商」的第一件工具。
   *
   * 打的是模型列表端点（`/models`），**不发一次推理**：只要拿到任何 HTTP 状态码，
   * 「Cloudflare 边缘到这个域名」这条路就是通的 —— 401 也算通（那只是密钥不对）。
   * 同时打**两个对照端点**（一个境外、一个国内可达，见 `data/providers.ts` 的 `CONTROLS`）：
   *
   * | 目标 | 对照 | 结论 |
   * | :-- | :-- | :-- |
   * | 有状态码 | —— | 通了，接下来看密钥与模型 |
   * | 超时 | 至少一个有状态码 | **这一家不通**（跨境被掐，或者它在拦云厂商出网 —— R37 那次就是） |
   * | 超时 | 两个都超时 | 出网整体有问题，与这家无关 |
   *
   * R37 那一整轮就是靠这个对照才把「代码写错」「密钥不对」「上游在拦我」三者分开的。
   * 把它做成一颗按钮，是为了下次不用再手搓一遍。
   */
  if (path === 'reach') {
    const p = new URL(req.url).searchParams;
    const base = (p.get('base') ?? '').trim().replace(/\/+$/, '');
    if (!/^https?:\/\/[^\s]+$/.test(base))
      return json({ ok: false, error: '端点要是一个完整的 http(s) 地址' }, CACHE.none, 400);

    const proto = asProto(p.get('proto'));
    // 探可达性不需要真密钥；填了就带上，那样 200 与 401 还能分得开
    const key = p.get('key') ?? 'probe';

    const hit = async (b: string, pr: Proto) => {
      const t0 = Date.now();
      const shape = SHAPES[pr];
      try {
        const res = await fetch(shape.listUrl(b, key), {
          headers: { ...CLIENT_HEADERS, ...shape.headers(key), accept: 'application/json' },
          signal: AbortSignal.timeout(REACH_TIMEOUT_MS),
        });
        // 响应体不要 —— 这里只关心「有没有响应」，读它只会多花时间
        try {
          await res.body?.cancel();
        } catch {
          /* 已经关了 */
        }
        return { ms: Date.now() - t0, status: res.status };
      } catch (e) {
        return { ms: Date.now() - t0, error: e instanceof Error ? e.message : String(e) };
      }
    };

    /* 三个一起打，总时长 = 最慢那个（10 秒），而不是三倍。
       对照组固定走 openai 形状：它就是 `<base>/models`，最省事的一条 */
    const [target, ...controls] = await Promise.all([
      hit(base, proto),
      ...CONTROLS.map((c) => hit(c.base, 'openai')),
    ]);

    const okTarget = 'status' in target;
    const okControl = controls.some((c) => 'status' in c);
    return json(
      {
        ok: true,
        target,
        controls: controls.map((c, i) => ({ label: CONTROLS[i].label, ...c })),
        verdict: okTarget ? 'reachable' : okControl ? 'blocked' : 'egress',
      },
      CACHE.none
    );
  }

  /**
   * 拉这家服务商下**所有有权限的模型**（R39 他要的「一键拉取」）。
   * 表单里填了 base/key/proto 就用填的（还没保存也能先拉），否则用主线的当前生效值。
   */
  if (path === 'models') {
    const p = new URL(req.url).searchParams;
    const now = (await loadCfg(env)).routes[0];
    const base = (p.get('base') || now.base).replace(/\/+$/, '');
    const key = p.get('key') || now.key;
    const proto = asProto(p.get('proto') || now.proto);

    if (!base || !key) return json({ ok: false, error: '先填端点与密钥' }, CACHE.none, 400);

    const shape = SHAPES[proto];
    try {
      const res = await fetch(shape.listUrl(base, key), {
        headers: { ...CLIENT_HEADERS, ...shape.headers(key), accept: 'application/json' },
        signal: AbortSignal.timeout(HEAD_TIMEOUT_MS),
      });
      const text = await res.text();
      if (!res.ok)
        return json({ ok: false, error: 'HTTP ' + res.status + '：' + text.slice(0, 160) }, CACHE.none, 502);

      const list = shape.listPick(JSON.parse(text) as Record<string, unknown>);
      // 名字排序，方便在几百个里找；上限 400 防着某些站返回上千条
      return json({ ok: true, models: list.sort().slice(0, 400) }, CACHE.none);
    } catch (e) {
      return json(
        { ok: false, error: e instanceof Error ? e.message : String(e) },
        CACHE.none,
        502
      );
    }
  }

  return adminWrite(req, env, path);
}

/** 写操作（save / test / 接管 / 草稿）—— 都要求已登录，调用方已经把门看住了 */
async function adminWrite(req: Request, env: Env, path: string): Promise<Response> {
  if (req.method !== 'POST') return fail(405, '只接 POST');

  let b: Record<string, unknown> = {};
  try {
    b = (await req.json()) as Record<string, unknown>;
  } catch {
    /* test 允许空体（用现有配置测）；save 空体等于什么都不改 */
  }

  const str = (v: unknown) => (typeof v === 'string' ? v.trim() : '');

  if (path === 'save') {
    const patch: Record<string, string> = {};

    /* ---- 线路（R41③）------------------------------------------------------
       整个数组一起存成一个 JSON。为什么不按键分开存（`base1`/`base2`…）：
       线路的**条数与顺序**本身就是配置的一部分，拆成散键之后「删掉中间那一条」
       要靠一堆删除操作去表达，很容易留下半条脏数据。

       **密钥留空 = 沿用这一条原来的密钥**（前端永远收不到密钥，所以它没法回填）。
       要清掉某条的密钥就填一个空格 —— 与 R39 的口径一致。 */
    if (Array.isArray(b.routes)) {
      const now = (await loadCfg(env)).routes;
      const routes = (b.routes as unknown[]).slice(0, ROUTE_MAX).map((r, i) => {
        const o = (r ?? {}) as Record<string, unknown>;
        const typed = str(o.key);
        return {
          base: str(o.base).replace(/\/+$/, ''),
          // 没填就沿用同一位置原来的那把（数组重排过的话这里会跟着位置走，见后台上的提示）
          key: typed || now[i]?.key || '',
          model: str(o.model),
          proto: asProto(o.proto),
          domestic: !!o.domestic,
        };
      });
      patch.routes = JSON.stringify(routes);
    }

    /* 老那五个键仍然认（R39 的格式）。它们现在只有一个用处：
       `routes` 被清空时的底座。写进来也不会与 `routes` 打架 —— `loadCfg` 里
       `routes` 有效就完全不看它们。 */
    for (const k of ['base', 'model', 'key', 'proto'] as const) if (k in b) patch[k] = str(b[k]);
    if ('off' in b) patch.off = b.off ? '1' : '';
    if ('domestic' in b) patch.domestic = b.domestic ? '1' : '';

    try {
      await cfgStub(env).fetch(
        new Request('https://chat.do/cfg-set', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(patch),
        })
      );
    } catch {
      return fail(502, '存不进去，再试一次');
    }
    return json({ ok: true, saved: Object.keys(patch) }, CACHE.none);
  }

  /* ---- 人工接管（R41②）--------------------------------------------------- */

  /** 打开／关掉某个会话的接管 */
  if (path === 'takeover') {
    const id = str(b.session);
    if (!SESSION_RE.test(id)) return fail(400, '会话号不对');
    try {
      await cfgStub(env).fetch(
        new Request('https://chat.do/takeover', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ id, on: !!b.on }),
        })
      );
    } catch {
      return fail(502, '改不了，再试一次');
    }
    return json({ ok: true, takeover: !!b.on }, CACHE.none);
  }

  /**
   * 沉麟本人回一句（R41②）。写进会话 DO，并放走正在挂着等的那条访客请求。
   *
   * **`tab`（窗口号）现在由后台指定**（R43）：会话是按 IP 合并的，一条会话下可能有
   * 好几个窗口，而「发给谁」不该靠猜。后台看得到每条消息属于哪个窗口，
   * 默认取最近一条访客消息的那个。不传也能工作（DO 那边有三级兜底），但那是退路。
   *
   * `waiting` 回给前端看：它是「这一句放走了几个人」——
   * 0 表示那个窗口此刻没有挂着的连接（对话框关了、或者空转到了上限），
   * 那这句话仍然进了记录，访客**下次打开对话框或发问时**会收到。
   */
  if (path === 'reply') {
    const id = str(b.session);
    if (!SESSION_RE.test(id)) return fail(400, '会话号不对');
    const text = str(b.text);
    if (!text) return fail(400, '说点什么');
    if ([...text].length > 2000) return fail(400, '一次最多 2000 个字');

    try {
      const res = await stubOf(env, id).fetch(
        new Request('https://chat.do/reply', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ text, tab: str(b.tab) }),
        })
      );
      const d = (await res.json()) as { waiting?: number; tab?: string };
      // 索引里的条数要跟上，否则会话列表上的「N 条」与记录里的行数对不上
      await touchSession(env, id, '', '沉麟本人', 1, 0);
      return json(
        { ok: true, waiting: Number(d.waiting) || 0, tab: String(d.tab ?? '') },
        CACHE.none
      );
    } catch {
      return fail(502, '没发出去，再试一次');
    }
  }

  /* ---- 草稿（R41②）------------------------------------------------------ */

  if (path === 'draft-save') {
    const coll = str(b.coll);
    const slug = str(b.slug);
    if (!['posts', 'notes', 'projects', 'photos', 'kb'].includes(coll))
      return fail(400, '不认识这个栏目');
    /* slug 就是文件名，也是 URL 的一段。只放行小写字母、数字、连字符与斜杠
       （斜杠是为了 `2026/foo` 这种子目录写法）—— 中文标题请他自己起一个英文 slug，
       本项目没有拼音库，猜出来的 slug 比让他填一个更糟 */
    if (!/^[a-z0-9][a-z0-9/-]{0,120}$/.test(slug))
      return fail(400, 'slug 只能用小写字母、数字、连字符与斜杠');

    try {
      await cfgStub(env).fetch(
        new Request('https://chat.do/draft-set', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({
            id: coll + '/' + slug,
            coll,
            slug,
            title: str(b.title),
            front: typeof b.front === 'string' ? b.front : '',
            body: typeof b.body === 'string' ? b.body : '',
          }),
        })
      );
    } catch {
      return fail(502, '存不进去，再试一次');
    }
    return json({ ok: true, id: coll + '/' + slug }, CACHE.none);
  }

  if (path === 'draft-del') {
    const id = str(b.id);
    if (!id) return fail(400, '缺 id');
    try {
      await cfgStub(env).fetch(
        new Request('https://chat.do/draft-del', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ id }),
        })
      );
    } catch {
      return fail(502, '删不掉，再试一次');
    }
    return json({ ok: true }, CACHE.none);
  }

  if (path === 'test') {
    const now = (await loadCfg(env)).routes;
    /* 测哪一条线路：前端会把下标一起传上来。表单里填了就用填的（还没保存也能先测），
       没填就用那一条的当前生效值 */
    const at = Math.max(0, Math.min(ROUTE_MAX - 1, Math.trunc(Number(b.at)) || 0));
    const mine = now[at] ?? now[0];
    const route: Route = {
      base: (str(b.base) || mine.base).replace(/\/+$/, ''),
      key: str(b.key) || mine.key,
      models: asModels(str(b.model) || mine.models.join(',')),
      proto: asProto(str(b.proto) || mine.proto),
      domestic: 'domestic' in b ? !!b.domestic : mine.domestic,
    };

    if (!route.base || !route.key || !route.models.length)
      return json({ ok: false, error: '端点、密钥、模型三样都要有' }, CACHE.none, 400);

    /**
     * `raw: true` —— 把**流式**响应的头几百字节原样吐回来。
     *
     * 这一条是 R39 加的，起因是一个查了很久的现象：非流式（测试台）能拿到完整回答，
     * 流式（真实对话）却一个字都没有。那种失败下唯一有用的信息就是「上游到底吐了什么」，
     * 而任何解析器都会把它吃掉。所以留一条不解析的通道。
     *
     * 只有已登录能打，与 probe 的 `error` 字段同一个口径（诊断必需，值不外泄给访客）。
     */
    if (b.raw) {
      const shape = SHAPES[route.proto];
      const model = route.models[0];
      try {
        const res = await fetch(shape.url(route.base, model, route.key), {
          method: 'POST',
          headers: {
            ...CLIENT_HEADERS,
            ...shape.headers(route.key),
            'content-type': 'application/json',
          },
          body: JSON.stringify(
            shape.body({
              model,
              system: '你只需要回答两个字：好的',
              turns: [{ role: 'user', content: '在吗' }],
              max: 64,
              temp: 0,
              stream: true,
            })
          ),
          signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
        });

        const ct = res.headers.get('content-type') ?? '';
        let raw = '';
        if (res.body) {
          const reader = res.body.getReader();
          const dec = new TextDecoder();
          while (raw.length < 900) {
            const { done, value } = await reader.read();
            if (done) break;
            raw += dec.decode(value as Uint8Array, { stream: true });
          }
          try {
            await reader.cancel();
          } catch {
            /* 已经关了 */
          }
        }
        return json({ ok: true, model, status: res.status, ct, raw: raw.slice(0, 900) }, CACHE.none);
      } catch (e) {
        return json(
          { ok: false, error: e instanceof Error ? e.message : String(e) },
          CACHE.none,
          502
        );
      }
    }

    /* 带真实的系统提示词去测，所以这里要先把知识库读出来。
       读不到就报出来 —— 那本身就是个要修的问题（对话也会因此走不通）。 */
    let kb: KbItem[];
    try {
      kb = await loadKb(env, req.url);
    } catch {
      return json({ ok: false, error: '知识库读不出来，先看 /kb.json 是不是空的' }, CACHE.none, 503);
    }

    /* 并行打，总时长 = 最慢那个（串行 6 个 ×30s 会撞上响应超时）。
       上限 6 个：subrequest 免费档 50，这里离得很远 */
    const results = await Promise.all(route.models.slice(0, 6).map((m) => probe(route, m, kb)));
    return json({ ok: true, kbCount: kb.length, results }, CACHE.none);
  }

  return fail(404, '没有这个接口');
}

export default {
  async fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    const url = new URL(request.url);

    /* 对话接口先分出去。它与下面那套点歌台的规则一条都不共用：POST 不是 GET、
       响应是流不是 JSON、而且**绝不能进边缘缓存**（缓存一次问答等于把一个人的
       回答发给下一个人）。同源检查这里自己做一遍。 */
    if (url.pathname === CHAT_PATH) {
      const from = request.headers.get('sec-fetch-site');
      if (from && from !== 'same-origin') return fail(403, '只服务本站页面');
      try {
        /* GET = 访客侧的主动接收通道（R43，长轮询）；POST = 发一句话。
           同一个路径两种方法，是为了不动 `wrangler.toml` 里 `run_worker_first`
           那条精确路径 —— 详见 `listen()` 的注释。 */
        if (request.method === 'GET') return await listen(request, env);
        return await chat(request, env, ctx);
      } catch {
        // chat() 里每一步都有兜底，走到这儿说明是没想到的情况 —— 也不能让它变成裸 500
        return fail(500, '我这边出了点问题，等一下再问');
      }
    }

    // 不是点歌接口就原样交回静态资源。`run_worker_first` 只列了那两条路径，
    // 但官方文档没写清 not_found_handling="404-page" 与「数组之外的路径是否仍进
    // Worker」的优先顺序，不赌 —— 这一条兜住，静态站的行为一点不变
    if (url.pathname.startsWith(ADMIN_PREFIX)) {
      /* 后台接口。同源检查同样自己做一遍：cookie 是 SameSite=Strict，
         但多一道不吃亏 —— 这一侧能改配置。 */
      const from = request.headers.get('sec-fetch-site');
      if (from && from !== 'same-origin') return fail(403, '只服务本站页面');
      try {
        return await admin(request, env);
      } catch {
        return fail(500, '后台这边出了点问题');
      }
    }

    if (!url.pathname.startsWith(API_PREFIX)) return env.ASSETS.fetch(request);

    if (request.method !== 'GET') return fail(405, '只接 GET');

    // 浏览器同源 fetch 是 same-origin；curl 根本不带这个头，所以本机验收照样能打。
    // 挡的是外站盗链与 iframe 嵌用，**挡不住脚本直刷** —— 这是「点歌全公开」的既定代价，
    // 不要以为这行是安全边界
    const site = request.headers.get('sec-fetch-site');
    if (site && site !== 'same-origin') return fail(403, '只服务本站页面');

    // `caches` 在 lib.dom 的 CacheStorage 类型里没有 `.default`（那是 Workers 独有的
    // 默认缓存区），而这里刻意不引 workers-types，所以就地断言一下
    const edge = (caches as unknown as { default: Cache }).default;

    const hit = await edge.match(request);
    if (hit) return hit;

    let res: Response;
    try {
      res = await route(url);
    } catch (e) {
      // route 里所有 throw 的 message 都是我自己写的中文，可以直接给访客看
      res = fail(502, e instanceof Error ? e.message : '曲库这边出问题了');
    }

    if (res.ok && res.headers.get('cache-control') !== CACHE.none) {
      ctx.waitUntil(edge.put(request, res.clone()));
    }
    return res;
  },
};




