/**
 * 本站的服务端代码 —— 两块：点歌台的取数接口，和「AI 版沉麟」的对话接口。
 *
 * 在这个文件出现之前，本站是纯 `[assets]` 的静态资源 Worker，没有一行代码在线上跑。
 * 加了 `wrangler.toml` 的 `main` 之后多了**运行期故障面**：这里抛异常就是线上 500。
 * 所以每一条路径都要有兜底，宁可返回一句中文人话，不要让异常裸奔。
 * 这道「单向门」第 11 轮已批准（原定 R6 阶段②走，点歌台把它提前了）。
 *
 * 做什么：
 * - `/api/music/*`：把浏览器不能直连的 `yinyueku.cn/api.php` 转成五条同源只读 GET。
 * - `/api/chat`：R6 阶段②。Workers AI + 整个知识库当依据，流式回答，回答完落库到
 *   Durable Object（R32 定的「改成落库、永久保留」）。
 *
 * 不做什么：**不中转媒体字节**。音频与封面的直链都自带 CORS（音频还带 Range），
 * 浏览器直接去 `music.126.net` / `p3.music.126.net` 拉，13 MB 的流量一个字节都不进
 * Worker 配额。
 *
 * 上游契约、四条坑、榜单白名单全在 `src/data/jukebox.ts` 的顶部注释里，改这里之前先看那个。
 * 对话那半边的模型选型账与提示词决议在 `src/data/chat.ts`。
 *
 * 缓存头必须在这里自己设：`public/_headers` **不作用于 Worker 生成的响应**
 * （官方文档原文 "Custom headers are not applied to responses generated by your
 * Worker code"）。静态资源仍走 `_headers`，两套互不相干。
 */
import {
  isChartId,
  LIST_MAX_N,
  SEARCH_MAX_N,
  SEARCH_MAX_Q,
  type JukeTrack,
} from './data/jukebox';
import {
  buildSystem,
  FALLBACK_MODEL,
  MAX_TOKENS,
  MSG_MAX,
  TEMPERATURE,
  type KbItem,
} from './data/chat';

/** DO 类必须从入口文件导出，`wrangler.toml` 的 `[exports.ChatLog]` 才找得到它 */
export { ChatLog } from './chat-log';

/**
 * 只声明用得到的绑定。**刻意不引 `@cloudflare/workers-types`** ——
 * 它的全局 `Request`/`Response` 会和 Astro 的 `lib.dom` 打架，
 * 为一个 Fetcher 类型换来全站类型冲突不值。
 */
interface Env {
  ASSETS: { fetch(req: Request): Promise<Response> };
  /** Workers AI。`[ai] binding = "AI"`，免费档 10,000 neurons/天 */
  AI: { run(model: string, input: Record<string, unknown>): Promise<unknown> };
  /** 对话落库。一个会话一个 DO 实例，名字就是会话 id */
  CHAT: {
    idFromName(name: string): unknown;
    get(id: unknown): { fetch(req: Request): Promise<Response> };
  };
  /**
   * 保险丝。R32 他选了「额度护栏先不设」，这不是护栏 —— 是出事时的关停开关：
   * `npx wrangler secret put CHAT_OFF`（值随便非空），`/api/chat` 立刻只回一句人话，
   * 不改代码、不重新构建、不影响点歌台。
   */
  CHAT_OFF?: string;
  /**
   * 对话上游的主路（R34）。三样一起给才生效，缺一样就退回 `env.AI`。
   * **值里有服务商信息，所以三样都只在 secret 里** —— 仓库是公开的，
   * 而他要求站上不体现这条链路的任何信息。代码里因此只有变量名。
   */
  CHAT_BASE?: string;
  CHAT_KEY?: string;
  CHAT_MODEL?: string;
  /**
   * 后台（`/admin`）的口令哈希与 cookie 签名密钥 —— R20② 那把锁，方案 B。
   *
   * `ADMIN_HASH` 格式：`pbkdf2$<迭代数>$<saltBase64>$<hashBase64>`。
   * 生成命令在 [部署运维](../docs/部署运维.md#后台口令) 里，**明文口令不进任何文件**。
   * 迭代数刻意只有一万：Workers Free 是 10 ms CPU／请求，而这把锁的威胁模型里
   * **哈希本身不可能泄漏**（只在 secret 里，不落库、不进仓库），
   * 离线爆破的前提不成立，所以不需要 OWASP 那个量级的慢哈希。
   *
   * 两样都没配时 `/admin` 会显示「还没设口令」并给出命令，**不会变成一把开着的锁**。
   */
  ADMIN_HASH?: string;
  ADMIN_SECRET?: string;
}

interface Ctx {
  waitUntil(p: Promise<unknown>): void;
}

const UPSTREAM = 'http://yinyueku.cn/api.php';

/** 上游是单点、证书都过期了，别让访客陪它一起等 */
const TIMEOUT_MS = 8000;

const API_PREFIX = '/api/music/';

/**
 * 各端点的缓存时长。
 *
 * `url` 一律不缓存。直链路径里带时间戳（`/20260822180905/`）：同一个 URL 连测
 * 6 分钟（0/60/180/360 秒）全是 206、总长恒为 11039085 —— 所以「播到一半链接
 * 过期」这条不成立，R14 拿它排除过一次误判。但**更长的有效期仍然未知**，
 * 而缓存一个已失效的直链的代价是「点了没声音」，收益只是省一次上游往返，
 * 不划算。择优选源那条路更不能缓存：它的结果取决于当时能探到的候选。
 *
 * `list` 只有 5 分钟：歌单是活的 —— 站主往「沉麟推荐」里加一首歌，不该等一小时
 * 才在站上看见（R23 就是这么报上来的：「改了歌单，刷新后没有变化」）。而且
 * `wrangler dev` 下这层缓存由 miniflare 持久化到 `.wrangler/state/v3/cache/`，
 * **重启进程也不清**，一小时的 TTL 在本地开发里就是一小时看不见改动。
 * 5 分钟仍然挡住了「一屏点开十次歌单」那种连续往返。
 *
 * `pic` 一天：封面直链是长期地址（自带 `max-age=31536000`，路径里没有 token 也没有
 * 时间戳），与 `url` 那条完全不同 —— 缓存它没有「过期了就没声音」的风险。
 */
const CACHE = {
  list: 'public, max-age=300',
  search: 'public, max-age=300',
  lyric: 'public, max-age=86400',
  pic: 'public, max-age=86400',
  none: 'no-store',
} as const;

/** LRC 时间戳。上游把错误信息也塞在 lyric 字段里，靠这个正则区分真歌词 */
const HAS_STAMP = /\[\d{1,3}:\d{1,2}/;

function json(data: unknown, cache: string, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': cache,
      // 接口不该被搜到，也不该给这个中文个人站招来音乐检索词
      'x-robots-tag': 'noindex',
    },
  });
}

/** 失败一律 no-store，不然会把一次上游抖动缓存一整天 */
const fail = (status: number, msg: string) => json({ error: msg }, CACHE.none, status);

/** 数字 id 也当字符串用；其余类型（null/对象）一律当缺失 */
function txt(v: unknown): string {
  if (typeof v === 'string') return v;
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return '';
}

function pick(data: unknown, key: string): string {
  return data && typeof data === 'object'
    ? txt((data as Record<string, unknown>)[key])
    : '';
}

/**
 * 打上游。抛出的 Error 的 message 全是我自己写的中文 ——
 * **上游响应体一个字都不外泄**（它的错误页是 HTML，里面还有它自己的路径）。
 */
async function upstream(params: Record<string, string>): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(UPSTREAM, {
      method: 'POST',
      // 这个头去掉上游就返回 HTML 错误页而不是 JSON（实测），不能省
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(params),
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    throw new Error('连不上曲库，等会儿再试');
  }

  if (!res.ok) throw new Error('曲库那边不太好（' + res.status + '）');

  const text = await res.text();
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new Error('曲库返回的不是 JSON');
  }
}

/** 一条上游记录 → 出口形状。缺关键字段就返回 null，宁可丢掉也不给前端半条 */
function toJuke(raw: unknown): JukeTrack | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  const songId = txt(r.id);
  const urlId = txt(r.url_id) || songId;
  const source = txt(r.source);
  const sign = txt(r.sign);
  if (!songId || !urlId || !source || !sign) return null;

  const artist = Array.isArray(r.artist)
    ? r.artist.map(txt).filter(Boolean).join(' / ')
    : txt(r.artist);

  return {
    songId,
    title: txt(r.name) || '未命名',
    artist,
    album: txt(r.album),
    urlId,
    lyricId: txt(r.lyric_id) || songId,
    // 封面 id **不进上面那道必填校验**：没有封面照样能播，不能因为缺它把整条候选判死
    picId: txt(r.pic_id),
    source,
    sign,
  };
}

function toList(data: unknown, limit: number): JukeTrack[] {
  if (!Array.isArray(data)) throw new Error('曲库返回的不是一个列表');
  const out: JukeTrack[] = [];
  for (const it of data) {
    const t = toJuke(it);
    if (t) out.push(t);
    if (out.length >= limit) break;
  }
  return out;
}

const clamp = (n: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, n));

/* ==========================================================================
   择优选源 —— 「部分 VIP 歌曲播不全」的真正解法

   R14 之前的判断是「上游对 VIP 只给 30 秒试听」，三轮实测把它推翻了：

   ① `br`（码率）参数无效：同一首歌 br=128/320/740/999/flac/不传，六种取值
      返回同一个 720813 B 的文件。所以「传个高码率就有完整版」是死路。
   ② 直链不是短命的：同一个 URL 连测 6 分钟全是 206，总长恒定。
   ③ **决定性的一条** —— 同一首歌、同一个源，两次搜索取到的东西不一样：
      《想你就写信 (Live)》第一轮 720813 B（≈0:18），第三轮 9550125 B（≈3:59）。
      而且同一次搜索的候选里，完整版与片段是**并排**的：
        《想你就写信》 tencent 9550376 B ≈3:59   ／ tencent  578573 B ≈0:14
        《不为谁而作的歌》tencent 10634755 B ≈4:26 ／ tencent 2552241 B ≈1:04
        《起风了》     tencent 12519132 B ≈5:13 ／ tencent 5215076 B ≈2:10
      原来的代码是「搜索结果第一条直接播」，第一条正好是片段时，
      看起来就完全像「这首 VIP 播不全」。

   所以这不是版权墙，是挑错了候选。修法：在**上游本来就免费返回**的同名候选里
   挑字节数最大的那条 —— 不涉及任何授权绕过，也不需要 VIP 凭据
   （Worker 是公开的，凭据一进去任何访客都能拿到解锁直链，等于替站长对外分发）。
   实测五首典型歌（想你就写信／晴天／不为谁而作的歌／恋人／起风了）5/5 都挑到完整版。
   ========================================================================== */

/**
 * 启动择优的字节下限。**它只决定「要不要去挑」，不用来判断完整性** ——
 * 实测的片段里有 5215076 B（《起风了》2:10，完整是 5:13）这种，
 * 绝对阈值判不出来。真正的判据是「候选里的最大值」。
 */
const MIN_FULL_BYTES = 2 * 1024 * 1024;

/** 并发探的候选上限。每条 1 次取链 + 1 次探头，6 条 = 12 个 subrequest，
    加首选与两次搜索共 16，离免费档的 50 还远。等待 I/O 不计入 CPU 时间，
    所以也撞不到 10ms 那条线 */
const PICK_MAX = 6;

/** 每源搜多少条。上游 count 是下限，20 够把同名的都捞进来 */
const PICK_COUNT = 20;

/**
 * 择优时搜哪些源。上游真实源只有三个：`netease`、`tencent`、`kugou`
 * （`kuwo`/`baidu`/`xiami` 退化成 tencent，`migu` 返回空）。
 * kugou 实测 8 次里 6 次取不到直链，不值得占一个候选名额。
 */
const PICK_SOURCES = ['netease', 'tencent'] as const;

/**
 * 归一化歌名／艺人用于比对：括号里的内容整段丢掉（`(Live)`、`（沉浸版）` 都是噪音），
 * 再去掉所有非字母非数字非汉字的字符并转小写。
 * 「想你就写信 (Live)」与「想你就写信」归一化后相等；「李荣浩-」「李荣浩.」都归一到「李荣浩」。
 */
function norm(s: string): string {
  return s
    .replace(/[(（[【][^)）\]】]*[)）\]】]/g, '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]/gu, '');
}

/**
 * 艺人算不算同一个。用包含关系而不是相等：上游的艺人字段常带脏尾巴或合作者
 * （实测有「李荣浩-」「李荣浩. / Sazablue」「周杰伦/李硕/达布希勒图/张鑫」），
 * 要求相等会把正确的候选全滤掉。任一侧为空就不作要求。
 */
function sameArtist(a: string, b: string): boolean {
  const x = norm(a);
  const y = norm(b);
  if (!x || !y) return true;
  return x.includes(y) || y.includes(x);
}

/**
 * 探这条直链有多少字节。`Range: bytes=0-9` 只拉 10 个字节，读的是响应头里的
 * `content-range: bytes 0-9/11039085` —— 音频字节仍然不进 Worker 配额。
 * 探不到返回 0：**这表示「不知道」，不表示「是片段」**，调用方要区分对待。
 */
async function probeBytes(link: string): Promise<number> {
  let res: Response;
  try {
    res = await fetch(link, {
      headers: { range: 'bytes=0-9' },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    return 0;
  }

  // 那 10 个字节也不留着占连接
  try {
    await res.body?.cancel();
  } catch {
    /* 已经关了就算了 */
  }

  const cr = res.headers.get('content-range') ?? '';
  if (cr.includes('/')) {
    const total = Number(cr.slice(cr.indexOf('/') + 1));
    if (Number.isFinite(total) && total > 0) return total;
  }

  // 不认 Range 的服务器会回 200 + 整个文件，这时 content-length 就是全长
  if (res.status === 200) {
    const len = Number(res.headers.get('content-length'));
    if (Number.isFinite(len) && len > 0) return len;
  }
  return 0;
}

/** 取一条直链。签名不对时上游返回 `{"url":"签名错误！"}`（HTTP 200、JSON 合法、
    字段名也对），所以必须看内容 —— 拿不到就返回空串 */
async function getLink(id: string, source: string, sign: string): Promise<string> {
  const link = pick(await upstream({ types: 'url', id, source, sign }), 'url');
  return link.startsWith('https://') ? link : '';
}

/** 一个源搜一次。搜不到／上游抖动都当「这个源没结果」——
    首选直链已经在手上了，不能让择优失败把整个请求带崩 */
async function searchIn(source: string, q: string): Promise<JukeTrack[]> {
  try {
    const data = await upstream({
      types: 'search',
      count: String(PICK_COUNT),
      pages: '1',
      name: q,
      source,
    });
    return toList(data, PICK_COUNT);
  } catch {
    return [];
  }
}

interface Cand {
  url: string;
  bytes: number;
}

/** 取链 + 探头，两步都可能失败，失败一律当 0 字节淘汰掉 */
async function weigh(t: JukeTrack): Promise<Cand> {
  try {
    const link = await getLink(t.urlId, t.source, t.sign);
    if (!link) return { url: '', bytes: 0 };
    return { url: link, bytes: await probeBytes(link) };
  } catch {
    return { url: '', bytes: 0 };
  }
}

/**
 * 在同名候选里找字节数最大的那条。找不到比 `floor` 更大的就返回 null。
 * `skip` 是首选的 `source:urlId`，它已经探过了，不重复花两个 subrequest。
 */
async function pickBest(
  name: string,
  artist: string,
  floor: number,
  skip: string,
): Promise<Cand | null> {
  const q = artist ? `${name} ${artist}` : name;
  const found = await Promise.all(PICK_SOURCES.map((s) => searchIn(s, q)));

  const want = norm(name);
  const seen = new Set<string>([skip]);
  const pool: JukeTrack[] = [];
  for (const list of found) {
    for (const t of list) {
      // 歌名要求归一化后相等（包含关系会把「老街」也算进「恋人」的候选）；
      // 艺人放宽到包含
      if (norm(t.title) !== want || !sameArtist(t.artist, artist)) continue;
      const key = `${t.source}:${t.urlId}`;
      if (seen.has(key)) continue;
      seen.add(key);
      pool.push(t);
      if (pool.length >= PICK_MAX) break;
    }
    if (pool.length >= PICK_MAX) break;
  }
  if (!pool.length) return null;

  const weighed = await Promise.all(pool.map(weigh));
  let best: Cand | null = null;
  for (const c of weighed) {
    if (c.url && c.bytes > floor && (!best || c.bytes > best.bytes)) best = c;
  }
  return best;
}

/* ==========================================================================
   AI 版沉麟 —— R6 阶段②

   整条链：浏览器 POST 一句话 → 这里拼「系统提示词 + 整个知识库 + 最近 3 轮」→
   Workers AI 流式吐字 → 流 tee 成两路，一路直给浏览器、一路自己读完写进 DO。

   **检索是「全给」，不是向量检索**：知识库现在 24 条、约 9000 tokens，Qwen3 的窗口
   是 32k，全塞进去比做检索更准也更简单（漏检的代价是「他明明写过却说没写过」）。
   代价是每次对话的输入 token 固定偏高 ≈ 每天 196 次。**条目涨到 60 条以上就得改**：
   那时输入会超过 2 万 token，一天只剩几十次。改法是先按关键词粗筛再拼，不必上向量库。
   ========================================================================== */

const CHAT_PATH = '/api/chat';

/** 会话 id 的形状（前端生成的 uuid）。它要当 DO 的名字用，所以字符集必须收紧 */
const SESSION_RE = /^[0-9a-f-]{8,64}$/i;

/** 知识库在 isolate 里缓存 5 分钟，省掉每次对话都读一遍 `/kb.json` 的 subrequest */
const KB_TTL_MS = 5 * 60 * 1000;
let kbCache: { at: number; items: KbItem[] } | null = null;

/**
 * 读知识库。走 `env.ASSETS.fetch('/kb.json')` —— 那是构建产物里的静态文件，
 * 由 `src/pages/kb.json.ts` 从 `src/content/kb/` 生成。
 * 这么绕是因为 `astro:content` 只存在于 Astro 构建期，这个文件 import 不到它。
 */
async function loadKb(env: Env, base: string): Promise<KbItem[]> {
  if (kbCache && Date.now() - kbCache.at < KB_TTL_MS) return kbCache.items;

  const res = await env.ASSETS.fetch(new Request(new URL('/kb.json', base)));
  if (!res.ok) throw new Error('知识库读不出来');

  const data = (await res.json()) as { items?: KbItem[] };
  const items = Array.isArray(data.items) ? data.items : [];
  // 空知识库比答错更糟：那会让模型完全靠自己编，而 R32 允许它编的前提是「有底座」
  if (!items.length) throw new Error('知识库是空的');

  kbCache = { at: Date.now(), items };
  return items;
}

const stubOf = (env: Env, session: string) => env.CHAT.get(env.CHAT.idFromName(session));

/**
 * 配置实例。`'config'` 不可能与会话号相撞 —— `SESSION_RE` 只放行 `[0-9a-f-]`，
 * 而这个名字里有 `n`、`g`、`i`、`o`。
 */
const cfgStub = (env: Env) => stubOf(env, 'config');

/** 一次对话真正用到的配置 */
interface Cfg {
  base: string;
  key: string;
  models: string[];
  off: boolean;
}

/**
 * 生效配置 = **后台改过的值覆盖 secret 里的默认值**。
 *
 * 为什么要能在后台改：这家上游的模型可用性会漂移（台账 R34 记的实测 —— 同一个模型
 * 20 分钟前还好，再调就「没有可用通道」）。改一次模型要走 `wrangler secret put` +
 * 重新 deploy 太慢，所以配置进 DO，后台存完立刻生效。
 *
 * 读不到 DO（它挂了、或者从没写过）就整份回落到 secret，功能不受影响。
 */
async function loadCfg(env: Env): Promise<Cfg> {
  let over: Record<string, string> = {};
  try {
    const res = await cfgStub(env).fetch(new Request('https://chat.do/cfg'));
    if (res.ok) over = ((await res.json()) as { cfg?: Record<string, string> }).cfg ?? {};
  } catch {
    /* 读不到就用 secret */
  }

  const model = over.model || env.CHAT_MODEL || '';

  return {
    base: (over.base || env.CHAT_BASE || '').replace(/\/+$/, ''),
    key: over.key || env.CHAT_KEY || '',
    models: model
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean),
    off: (over.off || env.CHAT_OFF || '') !== '',
  };
}

/** 往 DO 里追加一条。失败一律吞掉 —— 落库不该反过来把访客的对话弄坏 */
async function logMsg(
  env: Env,
  session: string,
  role: 'user' | 'ai',
  text: string,
  ip: string
): Promise<void> {
  try {
    await stubOf(env, session).fetch(
      new Request('https://chat.do/append', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ role, text, ip }),
      })
    );
  } catch {
    /* 存不进去也不能影响这一轮对话 */
  }
}

/** 取最近几轮当上下文。取不到就当没有历史，从头聊 —— 比整条请求失败好 */
async function loadHistory(env: Env, session: string): Promise<{ role: string; text: string }[]> {
  try {
    const res = await stubOf(env, session).fetch(new Request('https://chat.do/history'));
    if (!res.ok) return [];
    const d = (await res.json()) as { items?: { role?: string; text?: string }[] };
    return Array.isArray(d.items)
      ? d.items.map((i) => ({ role: String(i.role ?? ''), text: String(i.text ?? '') }))
      : [];
  } catch {
    return [];
  }
}

/** 有些模型会裹一层 `<think>…</think>`。落库前剥掉（前端另有一套，那是给流式过程看的） */
const strip = (s: string) =>
  s
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    .replace(/<\/?think>/gi, '')
    .trim();

/**
 * 从一行 SSE 的 payload 里抽出这一小段增量文本。
 *
 * 两种上游格式都认，因为主路与兜底路的格式不一样：
 * - OpenAI 兼容（主路）：`{"choices":[{"delta":{"content":"字"}}]}`
 * - Workers AI 绑定（兜底）：`{"response":"字"}`
 *
 * 认不出来就返回空串 —— 半行 JSON、心跳、注释行都走这条。
 */
function deltaOf(payload: string): string {
  if (!payload || payload === '[DONE]') return '';
  try {
    const j = JSON.parse(payload) as {
      response?: unknown;
      choices?: { delta?: { content?: unknown }; text?: unknown }[];
    };
    if (typeof j.response === 'string') return j.response;
    const c = j.choices?.[0];
    if (c) {
      if (typeof c.delta?.content === 'string') return c.delta.content;
      if (typeof c.text === 'string') return c.text;
    }
  } catch {
    /* 不是完整 JSON */
  }
  return '';
}

/** 把一段 SSE 文本切成整行，返回 [完整行数组, 剩下的半行] */
function lines(buf: string): [string[], string] {
  const parts = buf.split('\n');
  return [parts, parts.pop() ?? ''];
}

/**
 * 把 SSE 流读完并抽出正文。这一路是 `tee()` 出来的副本，
 * **客户端断开不影响它** —— 所以「访客问完就关页面」那种情况回答照样存得下来。
 */
async function collect(stream: ReadableStream): Promise<string> {
  const reader = stream.getReader();
  const dec = new TextDecoder();
  let buf = '';
  let out = '';

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += dec.decode(value as Uint8Array, { stream: true });
      const [rows, rest] = lines(buf);
      buf = rest;
      for (const row of rows) {
        if (!row.startsWith('data:')) continue;
        out += deltaOf(row.slice(5).trim());
      }
    }
  } catch {
    /* 上游断了：把已经收到的那部分存下来，半句也比丢掉好 */
  }

  return strip(out);
}

/**
 * 把上游 SSE 转成**本站自己的**格式：`data: {"d":"字"}`，收尾一条 `data: [DONE]`。
 *
 * 为什么要转而不是直通上游的字节：
 * - 前端只认一种格式，换上游不用动前端；
 * - **响应体里不留任何上游痕迹**（字段名、模型名、请求 id、usage 统计都会被丢掉）。
 *
 * **为什么手写 ReadableStream 而不用 `pipeThrough(new TransformStream(...))`**：
 * 上游中途断线或 `AbortSignal.timeout` 触发时，pipeThrough 会把错误往下游传播成一个
 * 未捕获的 rejection —— 本机实测过一次，`wrangler dev` 直接崩在
 * `Uncaught TimeoutError: The operation was aborted due to timeout`，线上则会变成 500。
 * 手写之后错误在 `pull()` 里被吞掉，客户端收到一个正常的 `[DONE]`，
 * **已经吐出来的字都保留**，只是提前收尾。
 */
function toSiteStream(upstream: ReadableStream): ReadableStream {
  const dec = new TextDecoder();
  const enc = new TextEncoder();
  const reader = upstream.getReader();
  let buf = '';

  const bye = (ctrl: { enqueue(c: Uint8Array): void; close(): void }) => {
    ctrl.enqueue(enc.encode('data: [DONE]\n\n'));
    ctrl.close();
  };

  return new ReadableStream({
    async pull(ctrl) {
      try {
        const { done, value } = await reader.read();
        if (done) return bye(ctrl);

        buf += dec.decode(value as Uint8Array, { stream: true });
        const [rows, rest] = lines(buf);
        buf = rest;

        let out = '';
        for (const row of rows) {
          if (!row.startsWith('data:')) continue;
          const d = deltaOf(row.slice(5).trim());
          if (d) out += `data: ${JSON.stringify({ d })}\n\n`;
        }
        if (out) ctrl.enqueue(enc.encode(out));
      } catch {
        bye(ctrl);
      }
    },
    cancel() {
      try {
        reader.cancel();
      } catch {
        /* 已经关了 */
      }
    },
  });
}

async function route(url: URL): Promise<Response> {
  const p = url.searchParams;

  switch (url.pathname.slice(API_PREFIX.length)) {
    case 'list': {
      const id = p.get('id') ?? '';
      // 白名单。少了这句，这就是个「任给 id 拉网易云歌单」的公开代理
      if (!isChartId(id)) return fail(400, '不认识这个榜单');
      const data = await upstream({ types: 'playlist', id, source: 'netease' });
      return json({ items: toList(data, LIST_MAX_N) }, CACHE.list);
    }

    case 'search': {
      const q = (p.get('q') ?? '').trim();
      if (!q) return fail(400, '要搜什么');
      // 用码点数而不是 .length：一个 emoji 是两个 UTF-16 单元，不该算两个字
      if ([...q].length > SEARCH_MAX_Q) return fail(400, `关键词最多 ${SEARCH_MAX_Q} 个字`);

      const n = clamp(Math.trunc(Number(p.get('n'))) || 12, 1, SEARCH_MAX_N);
      // 上游 count 是下限（count=10 会回 13 条），所以拿回来还得自己截到 n
      const data = await upstream({ types: 'search', count: String(n), pages: '1', name: q });
      return json({ items: toList(data, n) }, CACHE.search);
    }

    case 'url': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      if (!id || !source || !sign) return fail(400, '缺参数');

      const first = await getLink(id, source, sign);
      if (!first) return fail(502, '这首现在拿不到，换一首');

      // 没给歌名就没法择优 —— 原样返回，与择优上线前一模一样。
      // 榜单／搜索列表里点进来的都会带 name，不带的只有老前端
      const name = (p.get('name') ?? '').trim();
      if (!name) return json({ url: first }, CACHE.none);

      const artist = (p.get('artist') ?? '').trim();

      const bytes = await probeBytes(first);
      // 探不到大小就不折腾：既不能证明它是片段，而且连探头都失败了，
      // 后面那十几个请求大概也一样
      if (!bytes) return json({ url: first }, CACHE.none);
      if (bytes >= MIN_FULL_BYTES) return json({ url: first, bytes }, CACHE.none);

      const best = await pickBest(name, artist, bytes, `${source}:${id}`);
      const win = best ?? { url: first, bytes };

      const out: Record<string, unknown> = { url: win.url, bytes: win.bytes };
      // 换过源：前端可以据此知道播的不是它点的那条记录
      if (best) out.swapped = true;
      // 候选里最长的也还是偏短。不编造完整版，如实标出来让前端照实显示时长
      if (win.bytes < MIN_FULL_BYTES) out.short = true;
      return json(out, CACHE.none);
    }

    case 'lyric': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // song 是歌曲 id。lyric/pic 把它算进签名校验，漏了就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（歌词还要 song）');

      const data = await upstream({ types: 'lyric', id, source, song, sign });
      const lyric = pick(data, 'lyric');
      const tlyric = pick(data, 'tlyric');

      // 同上：错误信息也躺在 lyric 字段里。没有 [mm:ss 就一律当「这首没有词」，
      // 空字符串交给前端 —— 前端拿到空的就只是不显示歌词，不会把错误话当歌词唱出来
      if (!HAS_STAMP.test(lyric)) return json({ lyric: '', tlyric: '' }, CACHE.none);
      return json({ lyric, tlyric: HAS_STAMP.test(tlyric) ? tlyric : '' }, CACHE.lyric);
    }

    case 'pic': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // 与 lyric 同一个坑：pic 把歌曲 id 算进签名校验，漏了 song 就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（封面还要 song）');

      const data = await upstream({ types: 'pic', id, source, song, sign });
      const link = pick(data, 'url');
      // 「签名错误！」同样是 HTTP 200 + 合法 JSON + 对的字段名，所以看内容不看形状。
      // 前端拿到 502 就一直用文字标签 —— 没封面不影响听
      if (!link.startsWith('https://')) return fail(502, '这首没有封面');
      // 字节不经过 Worker：直链自带 `acao: *` 与一年的缓存，浏览器直接去 p3.music.126.net 拉
      return json({ url: link }, CACHE.pic);
    }

    default:
      return fail(404, '没有这个接口');
  }
}

/**
 * 等上游**响应头**的上限。拿到头之后就不限了 —— 用 `AbortSignal.timeout(总时长)`
 * 会把正常的长回答一起掐断。
 *
 * 12 秒是按线上实测定的：那家上游正常出字要 3–5 秒，而完全不通的时候 Cloudflare 侧
 * 要 **30 秒**才放弃。两个候选各等 30 秒、再加兜底，访客要盯着「…」看一分半 ——
 * 那比直接说答不上来更糟。
 */
const HEAD_TIMEOUT_MS = 12000;

/** 兜底（Workers AI 绑定）也要有上限。它 hang 住时同样不能让访客干等 */
const BIND_TIMEOUT_MS = 20000;

/** 探针（后台最小测试）用的上限。那是他自己在看，愿意多等一会儿换一个明确结论 */
const PROBE_TIMEOUT_MS = 30000;

type Msg = { role: string; content: string };

/**
 * 打上游时带的请求头。除了鉴权与 content-type，其余是一个**真实 OpenAI 客户端**
 * （`openai-node` SDK）会发的那一套 —— 裸 fetch 只带两个头，在按客户端做路由或
 * 限流的网关那儿容易被区别对待。这些头不含任何本站信息，也不含访客信息。
 */
const CLIENT_HEADERS: Record<string, string> = {
  accept: 'text/event-stream',
  'accept-language': 'zh-CN,zh;q=0.9,en;q=0.8',
  'user-agent': 'OpenAI/JS 4.104.0',
  'x-stainless-lang': 'js',
  'x-stainless-package-version': '4.104.0',
  'x-stainless-os': 'Windows',
  'x-stainless-arch': 'x64',
  'x-stainless-runtime': 'node',
  'x-stainless-runtime-version': 'v22.12.0',
  'x-stainless-retry-count': '0',
};

/**
 * 主路：OpenAI 兼容端点。地址、模型、密钥全部来自 secret ——
 * 这个函数里没有任何一个值是写在仓库里的。
 *
 * 抛出的 Error 的 message 只有我自己写的字 + HTTP 状态码，
 * **上游响应体一个字都不外泄**（它可能带自己的域名、模型名与报错细节）。
 */
async function askUpstream(cfg: Cfg, model: string, messages: Msg[]): Promise<ReadableStream> {
  /* 只给「建连 + 拿到响应头」设超时，拿到之后 `clearTimeout` —— 流式读取不受限。
     abort 会真正取消这次 fetch，不是只放弃等待。 */
  const ac = new AbortController();
  const timer = setTimeout(() => ac.abort(), HEAD_TIMEOUT_MS);

  let res: Response;
  try {
    res = await fetch(`${cfg.base}/chat/completions`, {
      method: 'POST',
      headers: {
        ...CLIENT_HEADERS,
        authorization: `Bearer ${cfg.key}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model,
        messages,
        stream: true,
        max_tokens: MAX_TOKENS,
        temperature: TEMPERATURE,
      }),
      signal: ac.signal,
    });
  } finally {
    clearTimeout(timer);
  }

  if (!res.ok || !res.body) throw new Error('上游 HTTP ' + res.status);
  return res.body;
}

/** 兜底：Workers AI 绑定。零密钥、零第三方，主路缺配置或这一次失败时走它 */
async function askBinding(env: Env, messages: Msg[]): Promise<ReadableStream> {
  /* `env.AI.run` 不收 AbortSignal，所以只能 race。**race 不会取消底层请求** ——
     它挂住的话那个 promise 会一直悬着（Worker 生命周期结束时才收），
     但至少访客不用陪它等。线上实测这个绑定在本账号上就是会挂（R37）。 */
  const out = await Promise.race([
    env.AI.run(FALLBACK_MODEL, {
      messages,
      stream: true,
      max_tokens: MAX_TOKENS,
      temperature: TEMPERATURE,
    }),
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('兜底 ' + BIND_TIMEOUT_MS + 'ms 没响应')), BIND_TIMEOUT_MS)
    ),
  ]);

  if (!(out instanceof ReadableStream)) throw new Error('绑定返回的不是流');
  return out;
}

/**
 * `POST /api/chat` —— 一句话进，一段流出。
 *
 * 失败一律返回 JSON + 一句中文人话，前端照原样显示给访客：
 * 这是唯一会被访客读到的错误文案，别在里面漏上游细节。
 */
async function chat(req: Request, env: Env, ctx: Ctx): Promise<Response> {
  if (req.method !== 'POST') return fail(405, '这个接口只接 POST');

  const cfg = await loadCfg(env);

  // 保险丝（R32：护栏先不设，但要有关停开关）。后台那个开关也走这一条
  if (cfg.off) return fail(503, '今天先不聊了，回头再来');

  let body: { session?: unknown; message?: unknown };
  try {
    body = (await req.json()) as typeof body;
  } catch {
    return fail(400, '请求体不是 JSON');
  }

  const session = typeof body.session === 'string' ? body.session : '';
  if (!SESSION_RE.test(session)) return fail(400, '会话号不对');

  const message = (typeof body.message === 'string' ? body.message : '').trim();
  if (!message) return fail(400, '说点什么');
  // 码点数而不是 .length：一个 emoji 是两个 UTF-16 单元，不该算两个字
  if ([...message].length > MSG_MAX) return fail(400, `一次最多 ${MSG_MAX} 个字`);

  let kb: KbItem[];
  try {
    kb = await loadKb(env, req.url);
  } catch {
    return fail(503, '知识库这会儿读不出来，等一下再问');
  }

  // R32 他定了要存 IP。这是 Cloudflare 注入的头，访客改不了
  const ip = req.headers.get('cf-connecting-ip') ?? '';

  const history = await loadHistory(env, session);

  const messages = [
    { role: 'system', content: buildSystem(kb) },
    ...history.map((h) => ({
      role: h.role === 'user' ? 'user' : 'assistant',
      content: h.text,
    })),
    { role: 'user', content: message },
  ];

  // 访客那条先落库：模型这一轮失败了，他说过的话也还在
  ctx.waitUntil(logMsg(env, session, 'user', message, ip));

  /* 三条路：主路的候选模型（`model` 可以写成逗号分隔的多个，按顺序试）→
     Workers AI 兜底。失败原因只进 Worker 日志，**不进响应体**。

     为什么要多候选：这家上游的模型可用性会漂移 —— 本机实测同一个模型 20 分钟前还好，
     再调就返「没有可用通道」。写两三个候选，第一个挂了自动换下一个，
     比直接掉到兜底（免费档 196 次/天）划算。 */
  if (!cfg.base || !cfg.key || !cfg.models.length) {
    /* 缺配置就整条主路不走。线上如果 secret 忘配、或者后台把它清空了，
       这一行是唯一能看出来的地方（只报有无，不报值） */
    console.warn(
      '主路没配全，直接走兜底 —— base:' +
        (cfg.base ? '有' : '无') +
        ' key:' +
        (cfg.key ? '有' : '无') +
        ' model:' +
        (cfg.models.length ? cfg.models.length + ' 个' : '无')
    );
  }

  let raw: ReadableStream | null = null;
  const why: string[] = [];

  if (cfg.base && cfg.key) {
    for (const m of cfg.models) {
      try {
        raw = await askUpstream(cfg, m, messages);
        break;
      } catch (e) {
        why.push('主路 ' + m + '：' + (e instanceof Error ? e.message : String(e)));
      }
    }
  }

  if (!raw) {
    try {
      raw = await askBinding(env, messages);
    } catch (e) {
      /* Workers AI 免费额度用完也走这儿（官方 pricing：超额后该类型操作直接报错，
         不自动计费也不降级） */
      why.push('兜底：' + (e instanceof Error ? e.message : String(e)));
    }
  }

  if (!raw) {
    console.error('两条路都没通 —— ' + why.join('｜'));
    return fail(502, '我这会儿答不上来，等一下再问');
  }

  if (why.length) console.warn('主路没走通，已退回兜底 —— ' + why.join('｜'));

  const [toClient, toLog] = raw.tee();
  ctx.waitUntil(
    collect(toLog).then((text) => (text ? logMsg(env, session, 'ai', text, '') : undefined))
  );

  return new Response(toSiteStream(toClient), {
    headers: {
      'content-type': 'text/event-stream; charset=utf-8',
      'cache-control': 'no-store',
      'x-robots-tag': 'noindex',
    },
  });
}

/* ==========================================================================
   后台 `/admin` —— R20② 那把锁（方案 B：自建口令 + 签名 cookie）＋ 模型配置台

   他要的三件事：藏起来、能实时改模型配置、能最小文本测试。
   - **藏起来**：不在任何导航里，靠登录保护。**不靠地址难猜** —— 那不是安全边界。
   - **实时改**：配置存 DO（`loadCfg`），存完下一次对话立刻生效，不用 deploy。
   - **最小测试**：`/api/admin/test` 用非流式、`max_tokens: 48` 打一次，
     把每个候选的耗时、状态码、正文、思考字数都报回来。上游漂移时这一页是唯一的确诊工具。

   `/admin` 那一页**照旧是公开可取的静态 HTML**（`public/_headers` 给 HTML 配了边缘缓存，
   而边缘缓存是共享的 —— 登录态一旦进 HTML 就会把一个人的页面发给另一个人）。
   所以那页里一个字的敏感内容都没有，全部由登录后的 fetch 填。
   ========================================================================== */

const ADMIN_PREFIX = '/api/admin/';

/** 登录有效期。七天 —— 够他隔几天回来看一次不用重新输 */
const SESSION_DAYS = 7;

const COOKIE = 'adm';

const enc = new TextEncoder();

const b64 = (buf: ArrayBuffer) => {
  let s = '';
  for (const b of new Uint8Array(buf)) s += String.fromCharCode(b);
  return btoa(s);
};

const unb64 = (s: string) => Uint8Array.from(atob(s), (c) => c.charCodeAt(0));

/**
 * 恒定时间比较。长度不同直接返回 false —— 长度本身不是秘密，
 * 而按位比完整个串才是重点（避免用响应时间猜出前缀）。
 */
function timingEq(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function pbkdf2(pass: string, salt: Uint8Array, iterations: number): Promise<string> {
  const key = await crypto.subtle.importKey('raw', enc.encode(pass), 'PBKDF2', false, [
    'deriveBits',
  ]);
  const bits = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt, iterations },
    key,
    256
  );
  return b64(bits);
}

/** `ADMIN_HASH` = `pbkdf2$<迭代数>$<saltB64>$<hashB64>`。格式不对一律当「口令错」 */
async function passOk(env: Env, pass: string): Promise<boolean> {
  const parts = (env.ADMIN_HASH ?? '').split('$');
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false;

  const iter = Number(parts[1]);
  // 上限是为了挡「有人把迭代数写成一亿」—— 那会把每次登录都变成一次 CPU 超时
  if (!Number.isFinite(iter) || iter < 1000 || iter > 200000) return false;

  try {
    return timingEq(await pbkdf2(pass, unb64(parts[2]), iter), parts[3]);
  } catch {
    return false;
  }
}

async function hmac(secret: string, payload: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    enc.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  return b64(await crypto.subtle.sign('HMAC', key, enc.encode(payload)));
}

/**
 * cookie 值 = `<过期毫秒>.<签名>`。**无状态** —— 不需要 KV、不需要记会话，
 * 所以 R6 那条「不落库」在鉴权这一侧一个字都不用动。
 */
const mintCookie = async (env: Env) => {
  const exp = String(Date.now() + SESSION_DAYS * 86400_000);
  return `${exp}.${await hmac(env.ADMIN_SECRET ?? '', exp)}`;
};

async function cookieOk(env: Env, req: Request): Promise<boolean> {
  // 两样 secret 缺一样就当没登录 —— 这把锁宁可锁死也不能开着
  if (!env.ADMIN_SECRET || !env.ADMIN_HASH) return false;

  const raw = (req.headers.get('cookie') ?? '')
    .split(';')
    .map((s) => s.trim())
    .find((s) => s.startsWith(COOKIE + '='));
  if (!raw) return false;

  const val = raw.slice(COOKIE.length + 1);
  const dot = val.indexOf('.');
  if (dot < 1) return false;

  const exp = val.slice(0, dot);
  const sig = val.slice(dot + 1);

  // 过期时间在签名覆盖范围内，所以把它改远一定失配
  if (!timingEq(await hmac(env.ADMIN_SECRET, exp), sig)) return false;
  return Number(exp) > Date.now();
}

const setCookie = (value: string, maxAge: number) =>
  `${COOKIE}=${value}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${maxAge}`;

/** 带 Set-Cookie 的 JSON 响应 */
const cookieJson = (data: unknown, cookie: string) =>
  new Response(JSON.stringify(data), {
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': 'no-store',
      'x-robots-tag': 'noindex',
      'set-cookie': cookie,
    },
  });

/**
 * 打一次上游，只为回答「这个模型现在能不能用」。
 * 非流式、一句最短的中文 —— 一次测试的成本可以忽略。
 *
 * `max_tokens` 给 300 而不是几十：**会思考的模型会先花掉一大截预算**。
 * 本机实测过一次误报 —— 给 48 的时候某个候选 HTTP 200、思考 217 字、正文一个字没有，
 * 于是被判成「不能用」，而它在真实对话（上限 700）里是好的。
 *
 * 返回里带 `think`（`reasoning_content` 的字数）就是为了让这种情况一眼能认出来：
 * `ok` 是 false 而 `think` 很大 = 预算被思考吃光，不是模型坏了。
 */
const PROBE_MAX_TOKENS = 300;

async function probe(cfg: Cfg, model: string): Promise<Record<string, unknown>> {
  const t0 = Date.now();
  try {
    const res = await fetch(`${cfg.base}/chat/completions`, {
      method: 'POST',
      headers: {
        ...CLIENT_HEADERS,
        accept: 'application/json',
        authorization: `Bearer ${cfg.key}`,
        'content-type': 'application/json',
      },
      body: JSON.stringify({
        model,
        messages: [{ role: 'user', content: '说三个字' }],
        max_tokens: PROBE_MAX_TOKENS,
        stream: false,
      }),
      signal: AbortSignal.timeout(PROBE_TIMEOUT_MS),
    });

    const ms = Date.now() - t0;
    const body = await res.text();

    // 上游的错误原文只回给**已登录的他自己**，这是诊断必需的（截断到 200 字）
    if (!res.ok) return { model, ok: false, ms, status: res.status, error: body.slice(0, 200) };

    try {
      const j = JSON.parse(body) as {
        choices?: { message?: { content?: string; reasoning_content?: string } }[];
      };
      const msg = j.choices?.[0]?.message;
      const out = strip(String(msg?.content ?? ''));
      const think = String(msg?.reasoning_content ?? '').length;
      return { model, ok: !!out, ms, status: res.status, text: out.slice(0, 120), think };
    } catch {
      return { model, ok: false, ms, status: res.status, error: '上游返回的不是 JSON' };
    }
  } catch (e) {
    return {
      model,
      ok: false,
      ms: Date.now() - t0,
      error: e instanceof Error ? e.message : String(e),
    };
  }
}

/**
 * `/api/admin/*`。五条：login / logout / state / save / test。
 *
 * 失败文案一律同一句「进不去」，**不区分「口令错」「没给口令」「还没设口令」** ——
 * 区分开就等于告诉对面「这个账号存在，只是密码不对」。
 */
async function admin(req: Request, env: Env): Promise<Response> {
  const path = new URL(req.url).pathname.slice(ADMIN_PREFIX.length);
  const ready = !!(env.ADMIN_HASH && env.ADMIN_SECRET);

  if (path === 'login') {
    if (req.method !== 'POST') return fail(405, '只接 POST');
    let pass = '';
    try {
      pass = String(((await req.json()) as { pass?: unknown }).pass ?? '');
    } catch {
      /* 请求体不对就当空口令，走同一条失败路径 */
    }
    if (!ready || !(await passOk(env, pass))) {
      /* 失败固定等一秒才回。**这是给短口令买的时间**：默认那个口令只有三位，
         不拖一下的话单线程几十秒就能穷举完。
         等待不计入 Workers 的 CPU 时间（10 ms/请求那条限制只算 CPU），所以这一秒是免费的。
         挡不住并发爆破 —— 真要挡得加失败计数与锁定，那需要状态，等他想换长口令时再说。

         ⚠ 口令的**值**一个字都不许出现在这个仓库里（它是公开的）。要看当前口令，
         去本机 `.dev.vars`（已被 .gitignore 排除）。 */
      await new Promise((r) => setTimeout(r, 1000));
      return json({ ok: false, error: '进不去' }, CACHE.none, 401);
    }
    return cookieJson({ ok: true }, setCookie(await mintCookie(env), SESSION_DAYS * 86400));
  }

  if (path === 'logout') return cookieJson({ ok: true }, setCookie('', 0));

  const logged = await cookieOk(env, req);

  /* 这一条**未登录也能打**，因为登录框要靠它知道「口令设了没有」——
     但未登录时除了这两个布尔值，一个字的配置都不返回 */
  if (path === 'state') {
    if (!logged) return json({ logged: false, ready }, CACHE.none);
    const cfg = await loadCfg(env);
    return json(
      {
        logged: true,
        ready,
        // key **永不回显**，只报有无
        cfg: { base: cfg.base, model: cfg.models.join(', '), hasKey: !!cfg.key, off: cfg.off },
        fallback: FALLBACK_MODEL,
      },
      CACHE.none
    );
  }

  if (!logged) return json({ ok: false, error: '进不去' }, CACHE.none, 401);

  return adminWrite(req, env, path);
}

/** save 与 test —— 都要求已登录，所以单独一段，调用方已经把门看住了 */
async function adminWrite(req: Request, env: Env, path: string): Promise<Response> {
  if (req.method !== 'POST') return fail(405, '只接 POST');

  let b: Record<string, unknown> = {};
  try {
    b = (await req.json()) as Record<string, unknown>;
  } catch {
    /* test 允许空体（用现有配置测）；save 空体等于什么都不改 */
  }

  const str = (v: unknown) => (typeof v === 'string' ? v.trim() : '');

  if (path === 'save') {
    const patch: Record<string, string> = {};
    // 只认这四个键。**空字符串是有意义的动作** —— 删掉这一项，回落到 secret 的默认值
    for (const k of ['base', 'model', 'key'] as const) if (k in b) patch[k] = str(b[k]);
    if ('off' in b) patch.off = b.off ? '1' : '';

    try {
      await cfgStub(env).fetch(
        new Request('https://chat.do/cfg-set', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify(patch),
        })
      );
    } catch {
      return fail(502, '存不进去，再试一次');
    }
    return json({ ok: true, saved: Object.keys(patch) }, CACHE.none);
  }

  if (path === 'test') {
    const now = await loadCfg(env);
    // 表单里填了就用填的（还没保存也能先测），没填就用当前生效值
    const cfg: Cfg = {
      base: (str(b.base) || now.base).replace(/\/+$/, ''),
      key: str(b.key) || now.key,
      models: (str(b.model) || now.models.join(','))
        .split(',')
        .map((s) => s.trim())
        .filter(Boolean),
      off: false,
    };

    if (!cfg.base || !cfg.key || !cfg.models.length)
      return json({ ok: false, error: '端点、密钥、模型三样都要有' }, CACHE.none, 400);

    /* 并行打，总时长 = 最慢那个（串行 6 个 ×30s 会撞上响应超时）。
       上限 6 个：subrequest 免费档 50，这里离得很远 */
    const results = await Promise.all(cfg.models.slice(0, 6).map((m) => probe(cfg, m)));
    return json({ ok: true, results }, CACHE.none);
  }

  return fail(404, '没有这个接口');
}

export default {
  async fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    const url = new URL(request.url);

    /* 对话接口先分出去。它与下面那套点歌台的规则一条都不共用：POST 不是 GET、
       响应是流不是 JSON、而且**绝不能进边缘缓存**（缓存一次问答等于把一个人的
       回答发给下一个人）。同源检查这里自己做一遍。 */
    if (url.pathname === CHAT_PATH) {
      const from = request.headers.get('sec-fetch-site');
      if (from && from !== 'same-origin') return fail(403, '只服务本站页面');
      try {
        return await chat(request, env, ctx);
      } catch {
        // chat() 里每一步都有兜底，走到这儿说明是没想到的情况 —— 也不能让它变成裸 500
        return fail(500, '我这边出了点问题，等一下再问');
      }
    }

    // 不是点歌接口就原样交回静态资源。`run_worker_first` 只列了那两条路径，
    // 但官方文档没写清 not_found_handling="404-page" 与「数组之外的路径是否仍进
    // Worker」的优先顺序，不赌 —— 这一条兜住，静态站的行为一点不变
    if (url.pathname.startsWith(ADMIN_PREFIX)) {
      /* 后台接口。同源检查同样自己做一遍：cookie 是 SameSite=Strict，
         但多一道不吃亏 —— 这一侧能改配置。 */
      const from = request.headers.get('sec-fetch-site');
      if (from && from !== 'same-origin') return fail(403, '只服务本站页面');
      try {
        return await admin(request, env);
      } catch {
        return fail(500, '后台这边出了点问题');
      }
    }

    if (!url.pathname.startsWith(API_PREFIX)) return env.ASSETS.fetch(request);

    if (request.method !== 'GET') return fail(405, '只接 GET');

    // 浏览器同源 fetch 是 same-origin；curl 根本不带这个头，所以本机验收照样能打。
    // 挡的是外站盗链与 iframe 嵌用，**挡不住脚本直刷** —— 这是「点歌全公开」的既定代价，
    // 不要以为这行是安全边界
    const site = request.headers.get('sec-fetch-site');
    if (site && site !== 'same-origin') return fail(403, '只服务本站页面');

    // `caches` 在 lib.dom 的 CacheStorage 类型里没有 `.default`（那是 Workers 独有的
    // 默认缓存区），而这里刻意不引 workers-types，所以就地断言一下
    const edge = (caches as unknown as { default: Cache }).default;

    const hit = await edge.match(request);
    if (hit) return hit;

    let res: Response;
    try {
      res = await route(url);
    } catch (e) {
      // route 里所有 throw 的 message 都是我自己写的中文，可以直接给访客看
      res = fail(502, e instanceof Error ? e.message : '曲库这边出问题了');
    }

    if (res.ok && res.headers.get('cache-control') !== CACHE.none) {
      ctx.waitUntil(edge.put(request, res.clone()));
    }
    return res;
  },
};




