/**
 * 本站唯一的服务端代码 —— 点歌台的取数接口。
 *
 * 在这个文件出现之前，本站是纯 `[assets]` 的静态资源 Worker，没有一行代码在线上跑。
 * 加了 `wrangler.toml` 的 `main` 之后多了**运行期故障面**：这里抛异常就是线上 500。
 * 所以每一条路径都要有兜底，宁可返回一句中文人话，不要让异常裸奔。
 * 这道「单向门」第 11 轮已批准（原定 R6 阶段②走，点歌台把它提前了）。
 *
 * 做什么：把浏览器不能直连的 `yinyueku.cn/api.php` 转成五条同源只读 GET。
 * 不做什么：**不中转媒体字节**。音频与封面的直链都自带 CORS（音频还带 Range），
 * 浏览器直接去 `music.126.net` / `p3.music.126.net` 拉，13 MB 的流量一个字节都不进
 * Worker 配额。
 *
 * 上游契约、四条坑、榜单白名单全在 `src/data/jukebox.ts` 的顶部注释里，改这里之前先看那个。
 *
 * 缓存头必须在这里自己设：`public/_headers` **不作用于 Worker 生成的响应**
 * （官方文档原文 "Custom headers are not applied to responses generated by your
 * Worker code"）。静态资源仍走 `_headers`，两套互不相干。
 */
import {
  isChartId,
  LIST_MAX_N,
  SEARCH_MAX_N,
  SEARCH_MAX_Q,
  type JukeTrack,
} from './data/jukebox';

/**
 * 只声明用得到的绑定。**刻意不引 `@cloudflare/workers-types`** ——
 * 它的全局 `Request`/`Response` 会和 Astro 的 `lib.dom` 打架，
 * 为一个 Fetcher 类型换来全站类型冲突不值。
 */
interface Env {
  ASSETS: { fetch(req: Request): Promise<Response> };
}

interface Ctx {
  waitUntil(p: Promise<unknown>): void;
}

const UPSTREAM = 'http://yinyueku.cn/api.php';

/** 上游是单点、证书都过期了，别让访客陪它一起等 */
const TIMEOUT_MS = 8000;

const API_PREFIX = '/api/music/';

/**
 * 各端点的缓存时长。
 *
 * `url` 一律不缓存。直链路径里带时间戳（`/20260822180905/`）：同一个 URL 连测
 * 6 分钟（0/60/180/360 秒）全是 206、总长恒为 11039085 —— 所以「播到一半链接
 * 过期」这条不成立，R14 拿它排除过一次误判。但**更长的有效期仍然未知**，
 * 而缓存一个已失效的直链的代价是「点了没声音」，收益只是省一次上游往返，
 * 不划算。择优选源那条路更不能缓存：它的结果取决于当时能探到的候选。
 *
 * `list` 只有 5 分钟：歌单是活的 —— 站主往「沉麟推荐」里加一首歌，不该等一小时
 * 才在站上看见（R23 就是这么报上来的：「改了歌单，刷新后没有变化」）。而且
 * `wrangler dev` 下这层缓存由 miniflare 持久化到 `.wrangler/state/v3/cache/`，
 * **重启进程也不清**，一小时的 TTL 在本地开发里就是一小时看不见改动。
 * 5 分钟仍然挡住了「一屏点开十次歌单」那种连续往返。
 *
 * `pic` 一天：封面直链是长期地址（自带 `max-age=31536000`，路径里没有 token 也没有
 * 时间戳），与 `url` 那条完全不同 —— 缓存它没有「过期了就没声音」的风险。
 */
const CACHE = {
  list: 'public, max-age=300',
  search: 'public, max-age=300',
  lyric: 'public, max-age=86400',
  pic: 'public, max-age=86400',
  none: 'no-store',
} as const;

/** LRC 时间戳。上游把错误信息也塞在 lyric 字段里，靠这个正则区分真歌词 */
const HAS_STAMP = /\[\d{1,3}:\d{1,2}/;

function json(data: unknown, cache: string, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: {
      'content-type': 'application/json; charset=utf-8',
      'cache-control': cache,
      // 接口不该被搜到，也不该给这个中文个人站招来音乐检索词
      'x-robots-tag': 'noindex',
    },
  });
}

/** 失败一律 no-store，不然会把一次上游抖动缓存一整天 */
const fail = (status: number, msg: string) => json({ error: msg }, CACHE.none, status);

/** 数字 id 也当字符串用；其余类型（null/对象）一律当缺失 */
function txt(v: unknown): string {
  if (typeof v === 'string') return v;
  if (typeof v === 'number' && Number.isFinite(v)) return String(v);
  return '';
}

function pick(data: unknown, key: string): string {
  return data && typeof data === 'object'
    ? txt((data as Record<string, unknown>)[key])
    : '';
}

/**
 * 打上游。抛出的 Error 的 message 全是我自己写的中文 ——
 * **上游响应体一个字都不外泄**（它的错误页是 HTML，里面还有它自己的路径）。
 */
async function upstream(params: Record<string, string>): Promise<unknown> {
  let res: Response;
  try {
    res = await fetch(UPSTREAM, {
      method: 'POST',
      // 这个头去掉上游就返回 HTML 错误页而不是 JSON（实测），不能省
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams(params),
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    throw new Error('连不上曲库，等会儿再试');
  }

  if (!res.ok) throw new Error('曲库那边不太好（' + res.status + '）');

  const text = await res.text();
  try {
    return JSON.parse(text) as unknown;
  } catch {
    throw new Error('曲库返回的不是 JSON');
  }
}

/** 一条上游记录 → 出口形状。缺关键字段就返回 null，宁可丢掉也不给前端半条 */
function toJuke(raw: unknown): JukeTrack | null {
  if (!raw || typeof raw !== 'object') return null;
  const r = raw as Record<string, unknown>;

  const songId = txt(r.id);
  const urlId = txt(r.url_id) || songId;
  const source = txt(r.source);
  const sign = txt(r.sign);
  if (!songId || !urlId || !source || !sign) return null;

  const artist = Array.isArray(r.artist)
    ? r.artist.map(txt).filter(Boolean).join(' / ')
    : txt(r.artist);

  return {
    songId,
    title: txt(r.name) || '未命名',
    artist,
    album: txt(r.album),
    urlId,
    lyricId: txt(r.lyric_id) || songId,
    // 封面 id **不进上面那道必填校验**：没有封面照样能播，不能因为缺它把整条候选判死
    picId: txt(r.pic_id),
    source,
    sign,
  };
}

function toList(data: unknown, limit: number): JukeTrack[] {
  if (!Array.isArray(data)) throw new Error('曲库返回的不是一个列表');
  const out: JukeTrack[] = [];
  for (const it of data) {
    const t = toJuke(it);
    if (t) out.push(t);
    if (out.length >= limit) break;
  }
  return out;
}

const clamp = (n: number, lo: number, hi: number) => Math.min(hi, Math.max(lo, n));

/* ==========================================================================
   择优选源 —— 「部分 VIP 歌曲播不全」的真正解法

   R14 之前的判断是「上游对 VIP 只给 30 秒试听」，三轮实测把它推翻了：

   ① `br`（码率）参数无效：同一首歌 br=128/320/740/999/flac/不传，六种取值
      返回同一个 720813 B 的文件。所以「传个高码率就有完整版」是死路。
   ② 直链不是短命的：同一个 URL 连测 6 分钟全是 206，总长恒定。
   ③ **决定性的一条** —— 同一首歌、同一个源，两次搜索取到的东西不一样：
      《想你就写信 (Live)》第一轮 720813 B（≈0:18），第三轮 9550125 B（≈3:59）。
      而且同一次搜索的候选里，完整版与片段是**并排**的：
        《想你就写信》 tencent 9550376 B ≈3:59   ／ tencent  578573 B ≈0:14
        《不为谁而作的歌》tencent 10634755 B ≈4:26 ／ tencent 2552241 B ≈1:04
        《起风了》     tencent 12519132 B ≈5:13 ／ tencent 5215076 B ≈2:10
      原来的代码是「搜索结果第一条直接播」，第一条正好是片段时，
      看起来就完全像「这首 VIP 播不全」。

   所以这不是版权墙，是挑错了候选。修法：在**上游本来就免费返回**的同名候选里
   挑字节数最大的那条 —— 不涉及任何授权绕过，也不需要 VIP 凭据
   （Worker 是公开的，凭据一进去任何访客都能拿到解锁直链，等于替站长对外分发）。
   实测五首典型歌（想你就写信／晴天／不为谁而作的歌／恋人／起风了）5/5 都挑到完整版。
   ========================================================================== */

/**
 * 启动择优的字节下限。**它只决定「要不要去挑」，不用来判断完整性** ——
 * 实测的片段里有 5215076 B（《起风了》2:10，完整是 5:13）这种，
 * 绝对阈值判不出来。真正的判据是「候选里的最大值」。
 */
const MIN_FULL_BYTES = 2 * 1024 * 1024;

/** 并发探的候选上限。每条 1 次取链 + 1 次探头，6 条 = 12 个 subrequest，
    加首选与两次搜索共 16，离免费档的 50 还远。等待 I/O 不计入 CPU 时间，
    所以也撞不到 10ms 那条线 */
const PICK_MAX = 6;

/** 每源搜多少条。上游 count 是下限，20 够把同名的都捞进来 */
const PICK_COUNT = 20;

/**
 * 择优时搜哪些源。上游真实源只有三个：`netease`、`tencent`、`kugou`
 * （`kuwo`/`baidu`/`xiami` 退化成 tencent，`migu` 返回空）。
 * kugou 实测 8 次里 6 次取不到直链，不值得占一个候选名额。
 */
const PICK_SOURCES = ['netease', 'tencent'] as const;

/**
 * 归一化歌名／艺人用于比对：括号里的内容整段丢掉（`(Live)`、`（沉浸版）` 都是噪音），
 * 再去掉所有非字母非数字非汉字的字符并转小写。
 * 「想你就写信 (Live)」与「想你就写信」归一化后相等；「李荣浩-」「李荣浩.」都归一到「李荣浩」。
 */
function norm(s: string): string {
  return s
    .replace(/[(（[【][^)）\]】]*[)）\]】]/g, '')
    .toLowerCase()
    .replace(/[^\p{L}\p{N}]/gu, '');
}

/**
 * 艺人算不算同一个。用包含关系而不是相等：上游的艺人字段常带脏尾巴或合作者
 * （实测有「李荣浩-」「李荣浩. / Sazablue」「周杰伦/李硕/达布希勒图/张鑫」），
 * 要求相等会把正确的候选全滤掉。任一侧为空就不作要求。
 */
function sameArtist(a: string, b: string): boolean {
  const x = norm(a);
  const y = norm(b);
  if (!x || !y) return true;
  return x.includes(y) || y.includes(x);
}

/**
 * 探这条直链有多少字节。`Range: bytes=0-9` 只拉 10 个字节，读的是响应头里的
 * `content-range: bytes 0-9/11039085` —— 音频字节仍然不进 Worker 配额。
 * 探不到返回 0：**这表示「不知道」，不表示「是片段」**，调用方要区分对待。
 */
async function probeBytes(link: string): Promise<number> {
  let res: Response;
  try {
    res = await fetch(link, {
      headers: { range: 'bytes=0-9' },
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });
  } catch {
    return 0;
  }

  // 那 10 个字节也不留着占连接
  try {
    await res.body?.cancel();
  } catch {
    /* 已经关了就算了 */
  }

  const cr = res.headers.get('content-range') ?? '';
  if (cr.includes('/')) {
    const total = Number(cr.slice(cr.indexOf('/') + 1));
    if (Number.isFinite(total) && total > 0) return total;
  }

  // 不认 Range 的服务器会回 200 + 整个文件，这时 content-length 就是全长
  if (res.status === 200) {
    const len = Number(res.headers.get('content-length'));
    if (Number.isFinite(len) && len > 0) return len;
  }
  return 0;
}

/** 取一条直链。签名不对时上游返回 `{"url":"签名错误！"}`（HTTP 200、JSON 合法、
    字段名也对），所以必须看内容 —— 拿不到就返回空串 */
async function getLink(id: string, source: string, sign: string): Promise<string> {
  const link = pick(await upstream({ types: 'url', id, source, sign }), 'url');
  return link.startsWith('https://') ? link : '';
}

/** 一个源搜一次。搜不到／上游抖动都当「这个源没结果」——
    首选直链已经在手上了，不能让择优失败把整个请求带崩 */
async function searchIn(source: string, q: string): Promise<JukeTrack[]> {
  try {
    const data = await upstream({
      types: 'search',
      count: String(PICK_COUNT),
      pages: '1',
      name: q,
      source,
    });
    return toList(data, PICK_COUNT);
  } catch {
    return [];
  }
}

interface Cand {
  url: string;
  bytes: number;
}

/** 取链 + 探头，两步都可能失败，失败一律当 0 字节淘汰掉 */
async function weigh(t: JukeTrack): Promise<Cand> {
  try {
    const link = await getLink(t.urlId, t.source, t.sign);
    if (!link) return { url: '', bytes: 0 };
    return { url: link, bytes: await probeBytes(link) };
  } catch {
    return { url: '', bytes: 0 };
  }
}

/**
 * 在同名候选里找字节数最大的那条。找不到比 `floor` 更大的就返回 null。
 * `skip` 是首选的 `source:urlId`，它已经探过了，不重复花两个 subrequest。
 */
async function pickBest(
  name: string,
  artist: string,
  floor: number,
  skip: string,
): Promise<Cand | null> {
  const q = artist ? `${name} ${artist}` : name;
  const found = await Promise.all(PICK_SOURCES.map((s) => searchIn(s, q)));

  const want = norm(name);
  const seen = new Set<string>([skip]);
  const pool: JukeTrack[] = [];
  for (const list of found) {
    for (const t of list) {
      // 歌名要求归一化后相等（包含关系会把「老街」也算进「恋人」的候选）；
      // 艺人放宽到包含
      if (norm(t.title) !== want || !sameArtist(t.artist, artist)) continue;
      const key = `${t.source}:${t.urlId}`;
      if (seen.has(key)) continue;
      seen.add(key);
      pool.push(t);
      if (pool.length >= PICK_MAX) break;
    }
    if (pool.length >= PICK_MAX) break;
  }
  if (!pool.length) return null;

  const weighed = await Promise.all(pool.map(weigh));
  let best: Cand | null = null;
  for (const c of weighed) {
    if (c.url && c.bytes > floor && (!best || c.bytes > best.bytes)) best = c;
  }
  return best;
}

async function route(url: URL): Promise<Response> {
  const p = url.searchParams;

  switch (url.pathname.slice(API_PREFIX.length)) {
    case 'list': {
      const id = p.get('id') ?? '';
      // 白名单。少了这句，这就是个「任给 id 拉网易云歌单」的公开代理
      if (!isChartId(id)) return fail(400, '不认识这个榜单');
      const data = await upstream({ types: 'playlist', id, source: 'netease' });
      return json({ items: toList(data, LIST_MAX_N) }, CACHE.list);
    }

    case 'search': {
      const q = (p.get('q') ?? '').trim();
      if (!q) return fail(400, '要搜什么');
      // 用码点数而不是 .length：一个 emoji 是两个 UTF-16 单元，不该算两个字
      if ([...q].length > SEARCH_MAX_Q) return fail(400, `关键词最多 ${SEARCH_MAX_Q} 个字`);

      const n = clamp(Math.trunc(Number(p.get('n'))) || 12, 1, SEARCH_MAX_N);
      // 上游 count 是下限（count=10 会回 13 条），所以拿回来还得自己截到 n
      const data = await upstream({ types: 'search', count: String(n), pages: '1', name: q });
      return json({ items: toList(data, n) }, CACHE.search);
    }

    case 'url': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      if (!id || !source || !sign) return fail(400, '缺参数');

      const first = await getLink(id, source, sign);
      if (!first) return fail(502, '这首现在拿不到，换一首');

      // 没给歌名就没法择优 —— 原样返回，与择优上线前一模一样。
      // 榜单／搜索列表里点进来的都会带 name，不带的只有老前端
      const name = (p.get('name') ?? '').trim();
      if (!name) return json({ url: first }, CACHE.none);

      const artist = (p.get('artist') ?? '').trim();

      const bytes = await probeBytes(first);
      // 探不到大小就不折腾：既不能证明它是片段，而且连探头都失败了，
      // 后面那十几个请求大概也一样
      if (!bytes) return json({ url: first }, CACHE.none);
      if (bytes >= MIN_FULL_BYTES) return json({ url: first, bytes }, CACHE.none);

      const best = await pickBest(name, artist, bytes, `${source}:${id}`);
      const win = best ?? { url: first, bytes };

      const out: Record<string, unknown> = { url: win.url, bytes: win.bytes };
      // 换过源：前端可以据此知道播的不是它点的那条记录
      if (best) out.swapped = true;
      // 候选里最长的也还是偏短。不编造完整版，如实标出来让前端照实显示时长
      if (win.bytes < MIN_FULL_BYTES) out.short = true;
      return json(out, CACHE.none);
    }

    case 'lyric': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // song 是歌曲 id。lyric/pic 把它算进签名校验，漏了就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（歌词还要 song）');

      const data = await upstream({ types: 'lyric', id, source, song, sign });
      const lyric = pick(data, 'lyric');
      const tlyric = pick(data, 'tlyric');

      // 同上：错误信息也躺在 lyric 字段里。没有 [mm:ss 就一律当「这首没有词」，
      // 空字符串交给前端 —— 前端拿到空的就只是不显示歌词，不会把错误话当歌词唱出来
      if (!HAS_STAMP.test(lyric)) return json({ lyric: '', tlyric: '' }, CACHE.none);
      return json({ lyric, tlyric: HAS_STAMP.test(tlyric) ? tlyric : '' }, CACHE.lyric);
    }

    case 'pic': {
      const id = p.get('id') ?? '';
      const source = p.get('source') ?? '';
      const sign = p.get('sign') ?? '';
      // 与 lyric 同一个坑：pic 把歌曲 id 算进签名校验，漏了 song 就永远只拿到「签名错误！」
      const song = p.get('song') ?? '';
      if (!id || !source || !sign || !song) return fail(400, '缺参数（封面还要 song）');

      const data = await upstream({ types: 'pic', id, source, song, sign });
      const link = pick(data, 'url');
      // 「签名错误！」同样是 HTTP 200 + 合法 JSON + 对的字段名，所以看内容不看形状。
      // 前端拿到 502 就一直用文字标签 —— 没封面不影响听
      if (!link.startsWith('https://')) return fail(502, '这首没有封面');
      // 字节不经过 Worker：直链自带 `acao: *` 与一年的缓存，浏览器直接去 p3.music.126.net 拉
      return json({ url: link }, CACHE.pic);
    }

    default:
      return fail(404, '没有这个接口');
  }
}

export default {
  async fetch(request: Request, env: Env, ctx: Ctx): Promise<Response> {
    const url = new URL(request.url);

    // 不是点歌接口就原样交回静态资源。`run_worker_first` 只列了 /api/music/*，
    // 但官方文档没写清 not_found_handling="404-page" 与「数组之外的路径是否仍进
    // Worker」的优先顺序，不赌 —— 这一条兜住，静态站的行为一点不变
    if (!url.pathname.startsWith(API_PREFIX)) return env.ASSETS.fetch(request);

    if (request.method !== 'GET') return fail(405, '只接 GET');

    // 浏览器同源 fetch 是 same-origin；curl 根本不带这个头，所以本机验收照样能打。
    // 挡的是外站盗链与 iframe 嵌用，**挡不住脚本直刷** —— 这是「点歌全公开」的既定代价，
    // 不要以为这行是安全边界
    const site = request.headers.get('sec-fetch-site');
    if (site && site !== 'same-origin') return fail(403, '只服务本站页面');

    // `caches` 在 lib.dom 的 CacheStorage 类型里没有 `.default`（那是 Workers 独有的
    // 默认缓存区），而这里刻意不引 workers-types，所以就地断言一下
    const edge = (caches as unknown as { default: Cache }).default;

    const hit = await edge.match(request);
    if (hit) return hit;

    let res: Response;
    try {
      res = await route(url);
    } catch (e) {
      // route 里所有 throw 的 message 都是我自己写的中文，可以直接给访客看
      res = fail(502, e instanceof Error ? e.message : '曲库这边出问题了');
    }

    if (res.ok && res.headers.get('cache-control') !== CACHE.none) {
      ctx.waitUntil(edge.put(request, res.clone()));
    }
    return res;
  },
};




